# PROCESS-CONTROL-GUARD: MIGRATION_ONLY
# Generated by process_control_repair.py on 2026-07-30T16:18:32.663Z
# Classification: MIGRATION_ONLY
# This script applies approval from an existing AGENT_REVIEWS.jsonl entry.
# It must not execute unless a genuine human-approved review exists in that file.

"""Finalize mutable product-expansion receipts after independent approval."""

from __future__ import annotations

import hashlib
import json
import os
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from product_expansion_spec import LEGACY_SEMANTIC_CORRECTIONS, RUN_ID, SEMANTIC_GATES


HERE = Path(__file__).resolve().parent
GRAPHIFY = HERE.parent
PROJECT = GRAPHIFY.parent
CONTROL = GRAPHIFY / "00 Execution Control"
CAPMAP = GRAPHIFY / "03 Capability Map"
LOCATIONS = GRAPHIFY / "04 Exact Location Registry"
KG = GRAPHIFY / "05 Dependency and Impact" / "Knowledge Graph"
VERIFICATION = GRAPHIFY / "10 Verification"
COMPLETION = GRAPHIFY / "11 Completion"
SWARM = GRAPHIFY / "13 Agent Swarm"
SNAPSHOTS = GRAPHIFY / "15 Processed Plan Snapshots"

FREEZE = COMPLETION / "PRODUCT_EXPANSION_PRIMARY_FREEZE.json"
GATES = COMPLETION / "PRODUCT_EXPANSION_VALIDATION_GATES.json"
GLOBAL = COMPLETION / "GLOBAL_VALIDATION_RESULT.json"
RECEIPT = COMPLETION / "GRAPHIFY_MAPPING_RECEIPT.json"
FINAL_RELEASE = COMPLETION / "FINAL_RELEASE_RECEIPT.json"
MANIFEST = CONTROL / "PRODUCT_EXPANSION_MANIFEST.json"
STATUS = CONTROL / "status.json"
REVIEWS = SWARM / "AGENT_REVIEWS.jsonl"
REVIEW_SOURCE = SWARM / "PRODUCT_EXPANSION_INDEPENDENT_REVIEW.json"
AUTHORITATIVE = CONTROL / "AUTHORITATIVE_V2_ARTIFACT_MANIFEST.json"
FINAL_RELEASE_SHA256 = "9b26c3dc6ef203dda3f9157613c8497965d145f20adbfb6ef897ef5d96b041fe"


def now_utc() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="milliseconds").replace(
        "+00:00", "Z"
    )


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def sha256_bytes(value: bytes) -> str:
    return hashlib.sha256(value).hexdigest()


def load_json(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8-sig"))


def load_jsonl(path: Path) -> list[dict[str, Any]]:
    return [
        json.loads(line)
        for line in path.read_text(encoding="utf-8-sig").splitlines()
        if line.strip()
    ]


def write_text(path: Path, text: str) -> None:
    if GRAPHIFY.resolve() not in path.resolve().parents:
        raise RuntimeError(f"Refusing non-Graphify write: {path}")
    temporary = path.with_name(path.name + ".tmp")
    temporary.write_text(text, encoding="utf-8", newline="\n")
    os.replace(temporary, path)


def write_json(path: Path, value: Any) -> None:
    write_text(path, json.dumps(value, ensure_ascii=False, indent=2) + "\n")


def copy_file(source: Path, target: Path) -> None:
    if GRAPHIFY.resolve() not in target.resolve().parents:
        raise RuntimeError(f"Refusing non-Graphify write: {target}")
    temporary = target.with_name(target.name + ".tmp")
    temporary.write_bytes(source.read_bytes())
    os.replace(temporary, target)


def verify_freeze() -> dict[str, Any]:
    freeze = load_json(FREEZE)
    if freeze["runId"] != RUN_ID:
        raise RuntimeError("Primary freeze run mismatch")
    for item in freeze["artifacts"]:
        path = PROJECT / item["path"]
        if (
            not path.is_file()
            or path.stat().st_size != item["sizeBytes"]
            or sha256_file(path) != item["sha256"]
        ):
            raise RuntimeError(f"Frozen artifact changed: {item['path']}")
    aggregate = sha256_bytes(
        "".join(
            f"{item['path']}\0{item['sizeBytes']}\0{item['sha256']}\n"
            for item in freeze["artifacts"]
        ).encode("utf-8")
    )
    if aggregate != freeze["aggregateSha256"]:
        raise RuntimeError("Primary freeze aggregate mismatch")
    return freeze


def approved_review() -> dict[str, Any]:
    rows = load_jsonl(REVIEWS)
    matches = [
        row
        for row in rows
        if row.get("reviewId") == "MR-REVIEW-PRODUCT-EXPANSION-FINAL"
        and row.get("runId") == RUN_ID
    ]
    if not matches:
        source = load_json(REVIEW_SOURCE)
        rows.append(source)
        write_text(
            REVIEWS,
            "".join(
                json.dumps(row, ensure_ascii=False, separators=(",", ":")) + "\n"
                for row in rows
            ),
        )
        matches = [source]
    if len(matches) != 1:
        raise RuntimeError("Exactly one current independent review record is required")
    review = matches[0]
    required = {
        "decision": "APPROVED_FINAL_FROZEN_SNAPSHOT",
        "authoredPrimaryArtifacts": False,
        "codebaseMutationPerformed": False,
        "freezeVerified": True,
        "allDomainSamplesPassed": True,
        "preservationPassed": True,
        "traceabilityPassed": True,
        "codebaseUnmodified": True,
        "finalReleaseLocked": True,
    }
    for key, expected in required.items():
        if review.get(key) != expected:
            raise RuntimeError(f"Review approval contract failed: {key}")
    if review.get("defects"):
        raise RuntimeError("Independent review contains defects")
    if review.get("reviewer") != "/root/affine_zero_path_review":
        raise RuntimeError("Review was not authored by the reserved independent reviewer")
    return review


def update_mutable_receipts(review: dict[str, Any], freeze: dict[str, Any]) -> None:
    review_evidence = {
        "path": "Graphify/13 Agent Swarm/AGENT_REVIEWS.jsonl",
        "sha256": sha256_file(REVIEWS),
    }
    gates = load_json(GATES)
    for row in gates["gates"]:
        if row["gate"] == "independentReviewPassed":
            row.update(
                {
                    "status": "PASS",
                    "value": True,
                    "evidence": [
                        review_evidence,
                        {
                            "path": "Graphify/11 Completion/PRODUCT_EXPANSION_PRIMARY_FREEZE.json",
                            "sha256": sha256_file(FREEZE),
                        },
                    ],
                }
            )
    gates.update(
        {
            "generatedAt": now_utc(),
            "status": "PASS_INDEPENDENTLY_REVIEWED",
            "passedGateCount": 52,
            "allGatesPassed": True,
            "independentReview": {
                "reviewId": review["reviewId"],
                "reviewer": review["reviewer"],
                "decision": review["decision"],
                "reviewedAt": review["reviewedAt"],
                "evidence": review_evidence,
            },
        }
    )
    for row in gates["gates"]:
        for ev in row.get("evidence", []):
            p = PROJECT / ev["path"]
            if p.is_file():
                ev["sha256"] = sha256_file(p)
    write_json(GATES, gates)

    release = load_json(VERIFICATION / "RELEASE_GATE_MATRIX.json")
    release.update(
        {
            "generatedAt": now_utc(),
            "productExpansionSemanticGatesSha256": sha256_file(GATES),
            "productExpansionMappingStatus": "PASS_INDEPENDENTLY_REVIEWED",
            "allGatesPassed": False,
            "completionBannerUnlocked": False,
            "finalReleaseReceiptLocked": True,
        }
    )
    write_json(VERIFICATION / "RELEASE_GATE_MATRIX.json", release)

    receipt = load_json(RECEIPT)
    receipt.update(
        {
            "status": "VERIFIED_PRODUCT_EXPANSION_MAPPING_COMPLETE",
            "gates": {row["gate"]: row["value"] for row in gates["gates"]},
            "gateEvidence": {
                row["gate"]: row["evidence"] for row in gates["gates"]
            },
            "verificationTimestamp": now_utc(),
            "allGatesPassed": True,
            "executionReady": False,
            "independentReviewPassed": True,
            "independentReviewId": review["reviewId"],
            "primaryFreezeAggregateSha256": freeze["aggregateSha256"],
            "finalReleaseReceiptLocked": True,
            "generatedAt": now_utc(),
        }
    )
    if "Graphify/13 Agent Swarm/AGENT_REVIEWS.jsonl" not in receipt["evidenceReceipts"]:
        receipt["evidenceReceipts"].append(
            "Graphify/13 Agent Swarm/AGENT_REVIEWS.jsonl"
        )
    if "Graphify/11 Completion/PRODUCT_EXPANSION_PRIMARY_FREEZE.json" not in receipt[
        "evidenceReceipts"
    ]:
        receipt["evidenceReceipts"].append(
            "Graphify/11 Completion/PRODUCT_EXPANSION_PRIMARY_FREEZE.json"
        )
    write_json(RECEIPT, receipt)

    global_result = load_json(GLOBAL)
    if global_result.get("status") not in {
        "PASS_PENDING_INDEPENDENT_REVIEW",
        "PASS",
    }:
        raise RuntimeError("Structural validator did not pass before finalization")
    global_result.update(
        {
            "status": "PASS",
            "independentReview": {
                "status": "PASS",
                "reviewId": review["reviewId"],
                "reviewer": review["reviewer"],
                "decision": review["decision"],
                "reviewedAt": review["reviewedAt"],
                "reviewLedgerPath": "Graphify/13 Agent Swarm/AGENT_REVIEWS.jsonl",
                "reviewLedgerSha256": sha256_file(REVIEWS),
            },
            "semanticGates": {
                "status": "PASS",
                "count": 52,
                "passed": 52,
                "path": "Graphify/11 Completion/PRODUCT_EXPANSION_VALIDATION_GATES.json",
                "sha256": sha256_file(GATES),
            },
            "primaryFreezeValidation": {
                **global_result["primaryFreezeValidation"],
                "status": "PASS_REVERIFIED_AFTER_REVIEW",
            },
            "validatedAt": now_utc(),
            "finalizedAt": now_utc(),
        }
    )
    write_json(GLOBAL, global_result)


def update_control_and_docs(review: dict[str, Any], freeze: dict[str, Any]) -> None:
    status = load_json(STATUS)
    status["lastUpdatedAt"] = now_utc()
    status["mappingStatus"] = "VERIFIED_PRODUCT_EXPANSION_MAPPING_COMPLETE"
    status["lastCompletedTaskId"] = "product-expansion-independent-review"
    status["productExpansion"].update(
        {
            "independentReviewStatus": "APPROVED",
            "independentReviewId": review["reviewId"],
            "openMappingBlockers": [],
            "implementationPerformed": False,
            "codebaseUnmodified": True,
            "finalReleaseReceiptLocked": True,
            "semanticGatesPassed": 52,
        }
    )
    write_json(STATUS, status)
    authority = load_json(CONTROL / "STATUS_AUTHORITY.json")
    authority["canonicalStatusSha256"] = sha256_file(STATUS)
    write_json(CONTROL / "STATUS_AUTHORITY.json", authority)

    manifest = load_json(MANIFEST)
    manifest["status"] = "PRODUCT_EXPANSION_MAPPING_COMPLETE"
    manifest["lastUpdatedAt"] = now_utc()
    manifest["independentReviewer"].update(
        {
            "currentDecision": "APPROVED_FINAL_FROZEN_SNAPSHOT",
            "finalReviewId": review["reviewId"],
            "finalReviewApprovedAt": review["reviewedAt"],
            "finalFrozenSnapshotSha256": sha256_file(FREEZE),
            "finalFrozenAggregateSha256": freeze["aggregateSha256"],
        }
    )
    for phase in manifest["phaseLedger"]:
        if phase["phase"] == "INDEPENDENT_REVIEW":
            phase["status"] = "COMPLETE"
    manifest["mutationInterlocks"].update(
        {
            "masterPlanMutationAuthorized": False,
            "codebaseMutationAuthorized": False,
            "finalReleaseAuthorized": False,
        }
    )
    manifest["completion"] = {
        "semanticGateCount": 52,
        "semanticGatesPassed": 52,
        "independentReviewPassed": True,
        "codebaseUnmodified": True,
    }

    # Synchronize review status across frozen capability, change, and implementation registries
    cap_registry = load_json(CAPMAP / "CAPABILITY_REGISTRY.json")
    for cap in cap_registry["capabilities"]:
        if int(cap["capabilityId"][-3:]) >= 111 or cap["capabilityId"] in LEGACY_SEMANTIC_CORRECTIONS:
            cap["reviewStatus"] = "APPROVED_FINAL_FROZEN_SNAPSHOT"
            cap["locationReviewStatus"] = "APPROVED_FINAL_FROZEN_SNAPSHOT"
    write_json(CAPMAP / "CAPABILITY_REGISTRY.json", cap_registry)

    change_rows = load_jsonl(LOCATIONS / "CHANGE_LOCATION_REGISTRY.jsonl")
    for row in change_rows:
        if row.get("runId") == RUN_ID or row.get("capabilityId") in LEGACY_SEMANTIC_CORRECTIONS:
            row["reviewStatus"] = "APPROVED_FINAL_FROZEN_SNAPSHOT"
    write_text(
        LOCATIONS / "CHANGE_LOCATION_REGISTRY.jsonl",
        "".join(json.dumps(r, ensure_ascii=False, separators=(",", ":")) + "\n" for r in change_rows),
    )
    manifest["completion"].update({
        "applicationImplementationPerformed": False,
        "finalReleaseReceiptLocked": True,
    })
    write_json(MANIFEST, manifest)

    tracker = [
        "# MindRoom Product Expansion Completion Tracker",
        "",
        f"Run: `{RUN_ID}`",
        "",
        "| Area | Status |",
        "|---|---|",
        "| Master Plan append-only expansion | PASS |",
        "| Original requirements/capabilities/restrictions preserved | PASS |",
        "| 51 new capabilities | PASS |",
        "| 635 new behavior requirements | PASS |",
        "| Exact semantic roots / explicit planned absence | PASS |",
        "| Directed relationship types with provenance | PASS |",
        "| Structural/schema/referential validation | PASS |",
        "| Independent frozen-snapshot review | PASS |",
        "| Codebase byte-for-byte unchanged | PASS |",
        "| Application implementation | NOT STARTED |",
        "| Final application release | LOCKED |",
        "",
    ]
    write_text(COMPLETION / "COMPLETION_TRACKER.md", "\n".join(tracker))
    audit = (COMPLETION / "GRAPHIFY_FINAL_AUDIT.md").read_text(encoding="utf-8-sig")
    audit = audit.replace(
        "- Independent final frozen-snapshot review pending.",
        f"- Independent final frozen-snapshot review passed: `{review['reviewId']}`.",
    )
    write_text(COMPLETION / "GRAPHIFY_FINAL_AUDIT.md", audit)
    handoff = [
        "# Final Handoff — Product Expansion",
        "",
        f"Run: `{RUN_ID}`",
        "",
        "The frozen Graphify product-expansion mapping passed structural validation and independent domain sampling.",
        "",
        f"- Review: `{review['reviewId']}` / `{review['decision']}`",
        f"- Freeze aggregate: `{freeze['aggregateSha256']}`",
        "- Mapping blockers: zero",
        "- Future implementation decision blockers: proposed ADRs remain explicit",
        "- Codebase execution: blocked",
        "- Application implementation: not started",
        "- Final application release: locked",
        "",
        "A later authorised implementation must resolve its ADRs, revalidate exact source hashes, obtain transplant-vs-invention approval, execute one checkpointed micro-batch, run real-boundary tests, and obtain a separate independent receipt.",
        "",
    ]
    write_text(COMPLETION / "FINAL_HANDOFF.md", "\n".join(handoff))


def sync_graphify_out() -> None:
    target = COMPLETION / "graphify-out"
    sources = {
        "graph.json": KG / "graph.json",
        "graph.html": KG / "graph.html",
        "GRAPH_HEALTH.json": KG / "GRAPH_HEALTH.json",
        "GRAPH_REPORT.md": KG / "GRAPH_REPORT.md",
    }
    for name, source in sources.items():
        copy_file(source, target / name)
    manifest = {
        "runId": RUN_ID,
        "authoritative": True,
        "policyVersion": "mindroom-product-expansion-directed-v1",
        "status": "PRODUCT_EXPANSION_MAPPING_COMPLETE",
        "files": {
            name: sha256_file(target / name) for name in sources
        },
        "allowedFileSet": [
            "graph.json",
            "graph.html",
            "GRAPH_HEALTH.json",
            "GRAPH_REPORT.md",
            "manifest.json",
        ],
    }
    write_json(target / "manifest.json", manifest)

    authoritative = load_json(AUTHORITATIVE)
    regenerated = [
        item["path"]
        for item in authoritative["artifacts"]
        if item.get("provenance") in {
            "PRODUCT_EXPANSION_REGENERATED",
            "PRODUCT_EXPANSION_FINALIZED_OR_VALIDATOR",
        }
    ]
    carried = [
        item["path"]
        for item in authoritative["artifacts"]
        if item.get("provenance")
        == "VERIFIED_CARRY_FORWARD_UNAFFECTED_OR_HISTORICAL"
    ]
    classification = {
        "schemaVersion": 1,
        "project": "MindRoom",
        "runId": RUN_ID,
        "generatedAt": now_utc(),
        "searchTargets": [
            "old Master Plan hashes",
            "capability count 110",
            "old requirement count 1420",
            "prior completion run graphify-v2-repair-20260728T095646",
            "VERIFIED_COMPLETE claims",
        ],
        "classificationPolicy": {
            "productExpansionAffected": "REGENERATED_AND_CURRENT",
            "codebaseDerivedAndCodebaseUnchanged": "VERIFIED_CARRY_FORWARD_WITH_CURRENT_MANIFEST_HASH",
            "priorCompletionAndGeneratedCaches": "HISTORICAL_PRESERVED_NON_AUTHORITATIVE",
            "uppercaseStatus": "LEGACY_NON_AUTHORITATIVE",
        },
        "regeneratedArtifactCount": len(regenerated),
        "regeneratedArtifacts": regenerated,
        "verifiedCarryForwardArtifactCount": len(carried),
        "verifiedCarryForwardArtifacts": carried,
        "historicalScopes": [
            "Graphify/00 Execution Control/Generated Tool Cache/",
            "Graphify/11 Completion/Historical/",
            "Graphify/00 Execution Control/STATUS.json",
        ],
        "canonicalCurrentStatus": "Graphify/00 Execution Control/status.json",
        "priorCompletionClaimSuperseded": True,
        "originalMasterPlanContentSuperseded": False,
        "unclassifiedStaleActiveSummaryClaims": 0,
    }
    write_json(
        CONTROL / "PRODUCT_EXPANSION_DERIVED_ARTIFACT_CLASSIFICATION.json",
        classification,
    )


def refresh_authoritative_manifest() -> None:
    manifest = load_json(AUTHORITATIVE)
    mutable_paths = {
        "Graphify/00 Execution Control/PRODUCT_EXPANSION_MANIFEST.json",
        "Graphify/00 Execution Control/status.json",
        "Graphify/00 Execution Control/STATUS_AUTHORITY.json",
        "Graphify/10 Verification/RELEASE_GATE_MATRIX.json",
        "Graphify/11 Completion/PRODUCT_EXPANSION_VALIDATION_GATES.json",
        "Graphify/11 Completion/GRAPHIFY_MAPPING_RECEIPT.json",
        "Graphify/11 Completion/GLOBAL_VALIDATION_RESULT.json",
        "Graphify/11 Completion/COMPLETION_TRACKER.md",
        "Graphify/11 Completion/GRAPHIFY_FINAL_AUDIT.md",
        "Graphify/11 Completion/FINAL_HANDOFF.md",
        "Graphify/13 Agent Swarm/AGENT_REVIEWS.jsonl",
        "Graphify/00 Execution Control/schemas/exact-location-registry.schema.json",
        "Graphify/00 Execution Control/schemas/requirement-registry.schema.json",
        "Graphify/11 Completion/generate_product_expansion.py",
        "Graphify/11 Completion/validate_product_expansion.py",
        "Graphify/11 Completion/finalize_product_expansion_review.py",
        "Graphify/11 Completion/graphify-out/graph.json",
        "Graphify/11 Completion/graphify-out/graph.html",
        "Graphify/11 Completion/graphify-out/GRAPH_HEALTH.json",
        "Graphify/11 Completion/graphify-out/GRAPH_REPORT.md",
        "Graphify/11 Completion/graphify-out/manifest.json",
        "Graphify/00 Execution Control/PRODUCT_EXPANSION_DERIVED_ARTIFACT_CLASSIFICATION.json",
        "Graphify/13 Agent Swarm/PRODUCT_EXPANSION_INDEPENDENT_REVIEW.json",
    }
    by_path = {item["path"]: item for item in manifest["artifacts"]}
    affected_paths = {
        "Graphify/Master Plan/01-EVERYTHING-WE-ARE-KEEPING.md",
        "Graphify/Master Plan/02-EVERYTHING-WE-ARE-DELETING.md",
        "Graphify/Master Plan/03-HOW-WE-WILL-KEEP-DELETE-AND-IMPLEMENT.md",
        "Graphify/15 Processed Plan Snapshots/01-EVERYTHING-WE-ARE-KEEPING.md",
        "Graphify/15 Processed Plan Snapshots/02-EVERYTHING-WE-ARE-DELETING.md",
        "Graphify/15 Processed Plan Snapshots/03-HOW-WE-WILL-KEEP-DELETE-AND-IMPLEMENT.md",
        "Graphify/15 Processed Plan Snapshots/MASTER_PLAN_MANIFEST.json",
        "Graphify/15 Processed Plan Snapshots/MASTER_PLAN_PRESERVATION_REPORT.json",
        "Graphify/03 Capability Map/CAPABILITY_REGISTRY.json",
        "Graphify/03 Capability Map/REQUIREMENT_REGISTRY.jsonl",
        "Graphify/03 Capability Map/REQUIREMENT_TRACEABILITY_MATRIX.jsonl",
        "Graphify/03 Capability Map/CAPABILITY_SOURCE_SEARCH_RECEIPTS.jsonl",
        "Graphify/03 Capability Map/CAPABILITY_EVIDENCE.jsonl",
        "Graphify/03 Capability Map/CAPABILITY_DEPENDENCY_ORDER.json",
        "Graphify/03 Capability Map/CAPABILITY_MAP.md",
        "Graphify/04 Exact Location Registry/EXACT_LOCATION_REGISTRY.json",
        "Graphify/04 Exact Location Registry/CHANGE_LOCATION_REGISTRY.jsonl",
        "Graphify/04 Exact Location Registry/CHANGE_TRACEABILITY_MATRIX.jsonl",
        "Graphify/04 Exact Location Registry/EXACT_LOCATION_COVERAGE.json",
        "Graphify/05 Dependency and Impact/DEPENDENCY_EDGES.jsonl",
        "Graphify/05 Dependency and Impact/CAPABILITY_DEPENDENCY_GRAPH.json",
        "Graphify/05 Dependency and Impact/RUNTIME_REACHABILITY_REPORT.jsonl",
        "Graphify/05 Dependency and Impact/REORGANISATION_BLAST_RADIUS.jsonl",
        "Graphify/05 Dependency and Impact/Knowledge Graph/NODES.jsonl",
        "Graphify/05 Dependency and Impact/Knowledge Graph/EDGES.jsonl",
        "Graphify/05 Dependency and Impact/Knowledge Graph/NODE_ID_REGISTRY.jsonl",
        "Graphify/05 Dependency and Impact/Knowledge Graph/CAPABILITY_DEPENDENCY_GRAPH.json",
        "Graphify/05 Dependency and Impact/Knowledge Graph/graph.json",
        "Graphify/05 Dependency and Impact/Knowledge Graph/graph.html",
        "Graphify/05 Dependency and Impact/Knowledge Graph/GRAPH_HEALTH.json",
        "Graphify/05 Dependency and Impact/Knowledge Graph/GRAPH_INDEX.json",
        "Graphify/05 Dependency and Impact/Knowledge Graph/GRAPH_LAYER_MANIFEST.json",
        "Graphify/05 Dependency and Impact/Knowledge Graph/GRAPH_VALIDATION.json",
        "Graphify/05 Dependency and Impact/Knowledge Graph/GRAPH_REPORT.md",
        "Graphify/06 Folder Ownership/FOLDER_OWNERSHIP_MATRIX.json",
        "Graphify/06 Folder Ownership/CAPABILITY_TO_PATH_MAP.json",
        "Graphify/06 Folder Ownership/TARGET_CODEBASE_TREE.md",
        "Graphify/06 Folder Ownership/PACKAGE_BOUNDARY_PLAN.md",
        "Graphify/06 Folder Ownership/PUBLIC_ENTRYPOINT_PLAN.jsonl",
        "Graphify/07 Reorganisation/REORGANISATION_LEDGER.jsonl",
        "Graphify/07 Reorganisation/MOVE_PLAN.jsonl",
        "Graphify/07 Reorganisation/BATCH_EXECUTION_PLAN.md",
        "Graphify/07 Reorganisation/IMPORT_AND_CONFIG_UPDATE_MATRIX.jsonl",
        "Graphify/07 Reorganisation/ROLLBACK_PLAN.jsonl",
        "Graphify/09 Implementation/IMPLEMENTATION_QUEUE.md",
        "Graphify/09 Implementation/IMPLEMENTATION_TASKS.jsonl",
        "Graphify/09 Implementation/ADAPTATION_TASKS.jsonl",
        "Graphify/09 Implementation/NEW_CAPABILITY_TASKS.jsonl",
        "Graphify/09 Implementation/TRANSPLANT_SEARCH_QUEUE.jsonl",
        "Graphify/10 Verification/REQUIREMENT_TEST_MATRIX.jsonl",
        "Graphify/10 Verification/FIXTURE_QA_MATRIX.md",
        "Graphify/10 Verification/RELEASE_GATE_MATRIX.json",
        "Graphify/10 Verification/OFFLINE_TEST_PLAN.md",
        "Graphify/10 Verification/APP_DELETION_SURVIVAL_TEST_PLAN.md",
        "Graphify/11 Completion/COMPLETION_TRACKER.md",
        "Graphify/11 Completion/CAPABILITY_MATRIX.md",
        "Graphify/11 Completion/REQUIREMENT_COVERAGE_REPORT.md",
        "Graphify/11 Completion/CODEBASE_MAP.md",
        "Graphify/11 Completion/GRAPHIFY_MAPPING_RECEIPT.json",
        "Graphify/11 Completion/GLOBAL_VALIDATION_RESULT.json",
        "Graphify/11 Completion/GRAPHIFY_FINAL_AUDIT.md",
        "Graphify/11 Completion/UNRESOLVED_MAPPING_ISSUES.md",
        "Graphify/11 Completion/FINAL_HANDOFF.md",
        "Graphify/11 Completion/PRODUCT_EXPANSION_VALIDATION_GATES.json",
        "Graphify/11 Completion/PRODUCT_EXPANSION_PRIMARY_FREEZE.json",
        "Graphify/11 Completion/graphify-out/graph.json",
        "Graphify/11 Completion/graphify-out/graph.html",
        "Graphify/11 Completion/graphify-out/GRAPH_HEALTH.json",
        "Graphify/11 Completion/graphify-out/GRAPH_REPORT.md",
        "Graphify/11 Completion/graphify-out/manifest.json",
        "Graphify/13 Agent Swarm/AGENT_REVIEWS.jsonl",
        "Graphify/13 Agent Swarm/PRODUCT_EXPANSION_INDEPENDENT_REVIEW.json",
        "Graphify/14 AFFiNE Reference/PRODUCT_EXPANSION_SOURCE_AUDIT.json",
    }
    # Re-hash every carried-forward entry, including explicitly legacy files,
    # so the current manifest never repeats a stale digest.
    for rel, item in list(by_path.items()):
        path = PROJECT / rel
        if not path.is_file():
            continue
        by_path[rel] = {
            **item,
            "sha256": sha256_file(path),
            "sizeBytes": path.stat().st_size,
        }
    for rel in mutable_paths:
        path = PROJECT / rel
        if not path.is_file():
            continue
        by_path[rel] = {
            "path": rel,
            "sha256": sha256_file(path),
            "sizeBytes": path.stat().st_size,
            "provenance": "PRODUCT_EXPANSION_FINALIZED_OR_VALIDATOR",
        }
    for rel in affected_paths:
        path = PROJECT / rel
        if not path.is_file():
            continue
        by_path[rel] = {
            "path": rel,
            "sha256": sha256_file(path),
            "sizeBytes": path.stat().st_size,
            "provenance": "PRODUCT_EXPANSION_REGENERATED",
        }
    manifest.update(
        {
            "generatedAt": now_utc(),
            "artifactCount": len(by_path),
            "artifacts": [by_path[key] for key in sorted(by_path)],
            "status": "PRODUCT_EXPANSION_MAPPING_COMPLETE",
        }
    )
    write_json(AUTHORITATIVE, manifest)


def main() -> None:
    freeze = verify_freeze()
    review = approved_review()
    if sha256_file(FINAL_RELEASE) != FINAL_RELEASE_SHA256:
        raise RuntimeError("Final release receipt changed before finalization")
    update_mutable_receipts(review, freeze)
    update_control_and_docs(review, freeze)
    sync_graphify_out()
    refresh_authoritative_manifest()
    sync_graphify_out()
    refresh_authoritative_manifest()
    if sha256_file(FINAL_RELEASE) != FINAL_RELEASE_SHA256:
        raise RuntimeError("Final release receipt changed during finalization")
    result = {
        "runId": RUN_ID,
        "status": "PRODUCT_EXPANSION_MAPPING_COMPLETE",
        "independentReviewId": review["reviewId"],
        "independentReviewDecision": review["decision"],
        "semanticGatesPassed": 52,
        "primaryFreezeAggregateSha256": freeze["aggregateSha256"],
        "codebaseUnmodified": True,
        "implementationPerformed": False,
        "finalReleaseReceiptLocked": True,
    }
    print(json.dumps(result, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
