"""Declarative MindRoom product-expansion mapping specification.

Paths are source-inspected semantic roots, never fixed-size search samples.
Target paths are planning records only and must not be created by this phase.
"""

from __future__ import annotations

import json
from pathlib import Path

_CONTROL = Path(__file__).resolve().parent.parent / "00 Execution Control"
if (_CONTROL / "FORENSIC_FINALIZATION_BASELINE.json").exists():
    with open(_CONTROL / "FORENSIC_FINALIZATION_BASELINE.json", "r", encoding="utf-8") as _f:
        RUN_ID = json.load(_f).get("runId", "mindroom-product-expansion-20260729-155104")
elif (_CONTROL / "FINALIZATION_BASELINE.json").exists():
    with open(_CONTROL / "FINALIZATION_BASELINE.json", "r", encoding="utf-8") as _f:
        RUN_ID = json.load(_f).get("runId", "mindroom-product-expansion-20260729-155104")
else:
    RUN_ID = "mindroom-product-expansion-20260729-155104"

SOURCE_CATALOG = {
    "calendar_engine": {
        "path": "Codebase/blocksuite/affine/data-view/src/view-presets/calendar",
        "classification": "AUTHORITATIVE_CORE_IMPLEMENTATION",
        "reason": "Mature local database calendar view model, rendering, layout, DnD, positioning, actions, and external-source seam.",
        "anchors": [
            "define.ts::calendarViewType",
            "define.ts::calendarViewModel",
            "calendar-view-manager.ts::CalendarSingleView",
            "source.ts::CalendarExternalSourceProvider",
            "pc/view.ts::CalendarViewUILogic",
        ],
    },
    "calendar_tests": {
        "path": "Codebase/blocksuite/affine/data-view/src/__tests__",
        "classification": "TEST_OR_FIXTURE",
        "reason": "Calendar unit and layout tests, including DST, clipping, overlap, all-day, failure, and interaction behavior.",
        "anchors": [
            "calendar.unit.spec.ts",
            "calendar-layout.unit.spec.ts",
        ],
    },
    "calendar_e2e": {
        "path": "Codebase/tests/blocksuite/e2e/database/calendar.spec.ts",
        "classification": "TEST_OR_FIXTURE",
        "reason": "Existing BlockSuite database calendar end-to-end behavior.",
        "anchors": ["calendar.spec.ts"],
    },
    "date_picker": {
        "path": "Codebase/packages/frontend/component/src/ui/date-picker/calendar",
        "classification": "USER_INTERFACE_ONLY",
        "reason": "Reusable date-selection UI; it is not calendar event persistence or domain ownership.",
        "anchors": ["calendar.tsx::Calendar", "day-picker.tsx::DayPicker"],
    },
    "journal_core": {
        "path": "Codebase/packages/frontend/core/src/modules/journal",
        "classification": "PARTIAL_REUSABLE_FOUNDATION",
        "reason": "Local journal identity/date behavior reusable for journal-calendar projection.",
        "anchors": ["services/journal.ts::JournalService", "store/journal.ts::JournalStore"],
    },
    "journal_calendar_ui": {
        "path": "Codebase/packages/frontend/core/src/desktop/pages/workspace/detail-page/tabs/journal/calendar-events.tsx",
        "classification": "CLOUD_COUPLED_IMPLEMENTATION",
        "reason": "Adjacent journal event UI coupled to integration/calendar cloud data and tracking.",
        "anchors": ["calendar-events.tsx::CalendarEvents"],
    },
    "calendar_workspace_bridge": {
        "path": "Codebase/packages/frontend/core/src/blocksuite/database-block/calendar/workspace-calendar-source.ts",
        "classification": "CLOUD_COUPLED_IMPLEMENTATION",
        "reason": "Optional server-backed external-source projection; yields no entries without WorkspaceServerService.",
        "anchors": [
            "workspace-calendar-source.ts::WorkspaceCalendarExternalSource",
            "workspace-calendar-source.ts::calendarEventToExternalEntry",
        ],
    },
    "calendar_integration": {
        "path": "Codebase/packages/frontend/core/src/modules/integration",
        "classification": "CLOUD_COUPLED_IMPLEMENTATION",
        "reason": "GraphQL-backed calendar accounts, calendars, event ranges, and registration; optional adapter evidence only.",
        "anchors": [
            "entities/calendar.ts::CalendarIntegration",
            "store/calendar.ts::CalendarStore",
        ],
    },
    "calendar_backend": {
        "path": "Codebase/packages/backend/server/src/plugins/calendar",
        "classification": "CLOUD_COUPLED_IMPLEMENTATION",
        "reason": "AFFiNE server Google/CalDAV integration, OAuth, jobs, queues, and remote sync; excluded from local core.",
        "anchors": [
            "service.ts::CalendarService",
            "providers/factory.ts::CalendarProviderFactory",
            "providers/caldav.ts::CalDAVProvider",
            "providers/google.ts::GoogleCalendarProvider",
        ],
    },
    "calendar_graphql": {
        "path": "Codebase/packages/common/graphql/src/graphql/calendar",
        "classification": "CLOUD_COUPLED_IMPLEMENTATION",
        "reason": "Remote GraphQL calendar operations; not local domain or file persistence.",
        "anchors": ["calendar-events.gql", "calendar-accounts.gql", "link-caldav-account.gql"],
    },
    "data_view_properties": {
        "path": "Codebase/blocksuite/affine/data-view/src/property-presets",
        "classification": "PARTIAL_REUSABLE_FOUNDATION",
        "reason": "Reusable date, number, text, select, multi-select, checkbox, progress, and image property UI/conversion.",
        "anchors": [
            "number/define.ts::NumberPropertySchema",
            "number/utils/formatter.ts::formatNumber",
            "date/define.ts",
            "select/define.ts",
        ],
    },
    "data_view_table": {
        "path": "Codebase/blocksuite/affine/data-view/src/view-presets/table",
        "classification": "PARTIAL_REUSABLE_FOUNDATION",
        "reason": "Reusable table view and row/property projections; not financial ledger ownership.",
        "anchors": [
            "define.ts::tableViewType",
            "table-view-manager.ts::TableSingleView",
        ],
    },
    "data_view_statistics": {
        "path": "Codebase/blocksuite/affine/data-view/src/core/statistics",
        "classification": "PARTIAL_REUSABLE_FOUNDATION",
        "reason": "Display aggregates such as sum, average, median, min, and max; not accounting-safe calculations.",
        "anchors": ["number.ts::numberStatsFunctions"],
    },
    "data_view_expression_false_positive": {
        "path": "Codebase/blocksuite/affine/data-view/src/core/expression",
        "classification": "FALSE_POSITIVE",
        "reason": "Filter literal/reference expressions, not a completed financial formula engine.",
        "anchors": ["types.ts", "ref/ref.ts"],
    },
    "database_model": {
        "path": "Codebase/blocksuite/affine/model/src/blocks/database",
        "classification": "PARTIAL_REUSABLE_FOUNDATION",
        "reason": "CRDT database block schema, columns, views, and stable block/row structures.",
        "anchors": ["database-model.ts::DatabaseBlockModel", "database-schema.ts::DatabaseBlockSchema"],
    },
    "database_block": {
        "path": "Codebase/blocksuite/affine/blocks/database/src",
        "classification": "PARTIAL_REUSABLE_FOUNDATION",
        "reason": "DatabaseBlockDataSource, property/view/store machinery, adapters, and UI projection.",
        "anchors": ["database-block.ts::DatabaseBlockComponent", "database-data-source.ts::DatabaseBlockDataSource"],
    },
    "data_view_block": {
        "path": "Codebase/blocksuite/affine/blocks/data-view/src",
        "classification": "PARTIAL_REUSABLE_FOUNDATION",
        "reason": "Generic BlockSuite data-view block integration.",
        "anchors": ["data-view-block.ts"],
    },
    "attachment_model": {
        "path": "Codebase/blocksuite/affine/model/src/blocks/attachment",
        "classification": "PARTIAL_REUSABLE_FOUNDATION",
        "reason": "Neutral attachment schema/model with name, size, MIME type, source ID, caption, and style metadata.",
        "anchors": ["attachment-model.ts::AttachmentBlockModel", "attachment-schema.ts::AttachmentBlockSchema"],
    },
    "attachment_block": {
        "path": "Codebase/blocksuite/affine/blocks/attachment/src",
        "classification": "PARTIAL_REUSABLE_FOUNDATION",
        "reason": "Blob-backed attachment rendering, adapters, previews, and interactions; telemetry/paywall coupling must be removed at use boundary.",
        "anchors": [
            "attachment-block.ts::AttachmentBlockComponent",
            "store.ts::AttachmentStoreExtension",
        ],
    },
    "chart_primitive": {
        "path": "Codebase/packages/frontend/admin/src/components/ui/chart.tsx",
        "classification": "PARTIAL_REUSABLE_FOUNDATION",
        "reason": "Generic Recharts wrapper in the admin package; finance dashboards remain absent and should not import admin ownership.",
        "anchors": ["chart.tsx::ChartContainer", "chart.tsx::ChartTooltipContent"],
    },
    "analytics_excluded": {
        "path": "Codebase/packages/frontend/core/src/desktop/pages/workspace/detail-page/tabs/analytics.tsx",
        "classification": "EXCLUDED_SYSTEM",
        "reason": "Cloud GraphQL analytics and subscription paywall; not MindRoom finance.",
        "anchors": ["analytics.tsx"],
    },
    "csv_adjacent": {
        "path": "Codebase/packages/frontend/admin/src/modules/accounts/utils/csv-utils.ts",
        "classification": "ADJACENT_IMPLEMENTATION",
        "reason": "Admin user-import CSV helper lacks finance quoting, dry-run, duplicate, rollback, and receipt semantics.",
        "anchors": ["csv-utils.ts::processCSVFile", "csv-utils.ts::downloadCsv"],
    },
    "local_storage": {
        "path": "Codebase/packages/common/nbstore/src/impls/sqlite",
        "classification": "PARTIAL_REUSABLE_FOUNDATION",
        "reason": "Local SQLite CRDT document/blob/index storage usable as editing cache, never sole file-backed source of truth.",
        "anchors": [
            "doc.ts::SqliteDocStorage",
            "blob.ts::SqliteBlobStorage",
            "indexer/index.ts::SqliteIndexerStorage",
        ],
    },
    "local_storage_core": {
        "path": "Codebase/packages/frontend/core/src/modules/storage",
        "classification": "PARTIAL_REUSABLE_FOUNDATION",
        "reason": "Local workspace storage service/facade; no canonical finance or calendar ordinary-file contracts.",
        "anchors": ["services/storage.ts", "index.ts"],
    },
    "safe_storage": {
        "path": "Codebase/packages/frontend/apps/electron/src/main/byok-storage/handlers.ts",
        "classification": "ADJACENT_IMPLEMENTATION",
        "reason": "Electron safeStorage precedent for encrypted local JSON values; not cross-platform finance encryption ownership.",
        "anchors": ["handlers.ts::registerByokStorageHandlers"],
    },
    "safe_json_storage": {
        "path": "Codebase/packages/frontend/apps/electron/src/main/shared-storage/json-file.ts",
        "classification": "PARTIAL_REUSABLE_FOUNDATION",
        "reason": "Persistent JSON file storage used by local encrypted-value precedent.",
        "anchors": ["json-file.ts::PersistentJSONFileStorage"],
    },
    "payment_system": {
        "path": "Codebase/packages/backend/server/src/plugins/payment",
        "classification": "EXCLUDED_SYSTEM",
        "reason": "AFFiNE monetisation, Stripe, RevenueCat, subscription, invoice, entitlement, and billing behavior; never MindRoom Finance.",
        "anchors": ["stripe.ts", "revenuecat/service.ts", "service.ts::PaymentService"],
    },
    "edgeless_root": {
        "path": "Codebase/blocksuite/affine/blocks/root/src/edgeless",
        "classification": "AUTHORITATIVE_CORE_IMPLEMENTATION",
        "reason": "Mature Edgeless root component/service, keyboard, clipboard, toolbars, CRUD, and interaction.",
        "anchors": [
            "edgeless-root-block.ts::EdgelessRootBlockComponent",
            "edgeless-root-service.ts::EdgelessRootService",
        ],
    },
    "surface_model": {
        "path": "Codebase/blocksuite/affine/blocks/surface/src",
        "classification": "AUTHORITATIVE_CORE_IMPLEMENTATION",
        "reason": "Surface Y.Map model, element CRUD, renderers, adapters/export, and commands.",
        "anchors": [
            "surface-model.ts::SurfaceBlockModel",
            "surface-model.ts::SurfaceBlockSchema",
        ],
    },
    "gfx_framework": {
        "path": "Codebase/blocksuite/framework/std/src/gfx",
        "classification": "AUTHORITATIVE_CORE_IMPLEMENTATION",
        "reason": "Generic GFX controller, models, views, grid, layers, tools, viewport, and selection.",
        "anchors": ["model/surface/surface-model.ts::SurfaceBlockModel"],
    },
    "affine_gfx": {
        "path": "Codebase/blocksuite/affine/gfx",
        "classification": "AUTHORITATIVE_CORE_IMPLEMENTATION",
        "reason": "Coherent AFFiNE brush, connector, group, link, mind-map, note, pointer, shape, template, text, and renderer packages.",
        "anchors": ["group/src/store.ts", "connector/src/connector-element.ts"],
    },
    "surface_ref": {
        "path": "Codebase/blocksuite/affine/model/src/blocks/surface-ref",
        "classification": "PARTIAL_REUSABLE_FOUNDATION",
        "reason": "Existing stable surface/document reference schema useful for cross-scope canvas references.",
        "anchors": ["surface-ref-model.ts::SurfaceRefBlockModel"],
    },
    "embed_doc": {
        "path": "Codebase/blocksuite/affine/blocks/embed-doc/src",
        "classification": "PARTIAL_REUSABLE_FOUNDATION",
        "reason": "Local linked/synced document embed UI and reference behavior.",
        "anchors": ["embed-linked-doc-block/embed-linked-doc-block.ts::EmbedLinkedDocBlockComponent"],
    },
    "folder_organize": {
        "path": "Codebase/packages/frontend/core/src/modules/organize",
        "classification": "ADJACENT_IMPLEMENTATION",
        "reason": "Logical navigation folder tree and links, not filesystem ownership or durable folder scope.",
        "anchors": ["stores/folder.ts::FolderStore", "services/organize.ts"],
    },
    "collection_rules": {
        "path": "Codebase/packages/frontend/core/src/modules/collection-rules",
        "classification": "PARTIAL_REUSABLE_FOUNDATION",
        "reason": "Dynamic filter/group/order rules useful for folder-content projections.",
        "anchors": ["impls/filters", "impls/group-by", "impls/order-by"],
    },
    "id_generator": {
        "path": "Codebase/blocksuite/framework/store/src/utils/id-generator.ts",
        "classification": "AUTHORITATIVE_CORE_IMPLEMENTATION",
        "reason": "Existing nanoid/UUID generators and stable in-document IDs must be preserved for compatibility.",
        "anchors": ["id-generator.ts::nanoid", "id-generator.ts::uuidv4"],
    },
    "workspace_identity": {
        "path": "Codebase/packages/frontend/core/src/modules/workspace/impls/workspace.ts",
        "classification": "PARTIAL_REUSABLE_FOUNDATION",
        "reason": "Stable workspace/doc IDs and optional supplied IDs; paths are not identity.",
        "anchors": ["workspace.ts::WorkspaceImpl", "workspace.ts::idGenerator"],
    },
    "doc_identity": {
        "path": "Codebase/packages/frontend/core/src/modules/doc/stores/docs.ts",
        "classification": "PARTIAL_REUSABLE_FOUNDATION",
        "reason": "Existing stable document IDs generated independently from file paths.",
        "anchors": ["docs.ts::DocsStore", "docs.ts::nanoid"],
    },
    "mindmap_model": {
        "path": "Codebase/blocksuite/affine/model/src/elements/mindmap",
        "classification": "AUTHORITATIVE_CORE_IMPLEMENTATION",
        "reason": "Real non-AI MindmapElementModel tree, stable child IDs, serialization, layout state, loop protection, collapse, reparent, and style.",
        "anchors": [
            "mindmap.ts::MindmapElementModel",
            "mindmap.ts::MindmapNode",
            "mindmap.ts::MindmapRoot",
        ],
    },
    "mindmap_gfx": {
        "path": "Codebase/blocksuite/affine/gfx/mindmap/src",
        "classification": "AUTHORITATIVE_CORE_IMPLEMENTATION",
        "reason": "Real non-AI layout, renderer, drag interaction, toolbar, import, and adapters.",
        "anchors": [
            "view/layout.ts::layout",
            "store.ts::MindmapStoreExtension",
            "interactivity/mind-map-drag.ts",
        ],
    },
    "mindmap_registration": {
        "path": "Codebase/blocksuite/affine/all/src/gfx/mindmap",
        "classification": "AUTHORITATIVE_CORE_IMPLEMENTATION",
        "reason": "Mind-map BlockSuite registration and public composition.",
        "anchors": ["store.ts", "view.ts"],
    },
    "mindmap_tests": {
        "path": "Codebase/blocksuite/integration-test/src/__tests__/edgeless/mindmap.spec.ts",
        "classification": "TEST_OR_FIXTURE",
        "reason": "Non-AI mind-map integration behavior including layout, cycles, collapse, undo, reorder, and reparent.",
        "anchors": ["mindmap.spec.ts"],
    },
    "mindmap_ai": {
        "path": "Codebase/packages/frontend/core/src/blocksuite/ai/mini-mindmap",
        "classification": "EXCLUDED_SYSTEM",
        "reason": "AI-generated mini mind-map implementation; explicitly not the retained mind-map foundation.",
        "anchors": ["mindmap-service.ts", "mindmap-preview.ts"],
    },
    "reference_model": {
        "path": "Codebase/blocksuite/affine/model/src/consts/doc.ts",
        "classification": "AUTHORITATIVE_CORE_IMPLEMENTATION",
        "reason": "ReferenceInfo/ReferenceParams schemas with page, block, element, database, row, and spatial identifiers.",
        "anchors": ["doc.ts::ReferenceParamsSchema", "doc.ts::ReferenceInfoSchema"],
    },
    "inline_reference": {
        "path": "Codebase/blocksuite/affine/inlines/reference/src",
        "classification": "AUTHORITATIVE_CORE_IMPLEMENTATION",
        "reason": "Explicit local document/block/element reference model, adapters, rendering, and interaction.",
        "anchors": ["reference-node/reference-node.ts::AffineReference"],
    },
    "linked_doc": {
        "path": "Codebase/blocksuite/affine/widgets/linked-doc/src",
        "classification": "PARTIAL_REUSABLE_FOUNDATION",
        "reason": "Linked-document widget and local document navigation/import behavior.",
        "anchors": ["widget.ts", "linked-doc-popover.ts"],
    },
    "doc_links": {
        "path": "Codebase/packages/frontend/core/src/modules/doc-link",
        "classification": "PARTIAL_REUSABLE_FOUNDATION",
        "reason": "Explicit links and derived backlinks using indexed refDocId; remote preference must be removed.",
        "anchors": [
            "entities/doc-links.ts::DocLinks",
            "entities/doc-backlinks.ts::DocBacklinks",
        ],
    },
    "reader_refs": {
        "path": "Codebase/packages/common/reader/src/reader.ts",
        "classification": "PARTIAL_REUSABLE_FOUNDATION",
        "reason": "Extracts reference fields, parents, database relations, and markdown preview from BlockSuite documents.",
        "anchors": ["reader.ts::Reader"],
    },
    "indexer_schema": {
        "path": "Codebase/packages/common/nbstore/src/storage/indexer/schema.ts",
        "classification": "PARTIAL_REUSABLE_FOUNDATION",
        "reason": "Local index fields for refDocId and rebuildable search-derived relationships.",
        "anchors": ["schema.ts::IndexerSchema"],
    },
    "sqlite_indexer": {
        "path": "Codebase/packages/common/nbstore/src/impls/sqlite/indexer",
        "classification": "PARTIAL_REUSABLE_FOUNDATION",
        "reason": "Local SQLite full-text/reference index; derived cache only.",
        "anchors": ["index.ts::SqliteIndexerStorage"],
    },
    "embedding_cloud": {
        "path": "Codebase/packages/frontend/core/src/modules/workspace-indexer-embedding",
        "classification": "EXCLUDED_SYSTEM",
        "reason": "Current embedding UI/service is coupled to cloud/vector AI and is not the authoritative local semantic-link engine.",
        "anchors": ["services/embedding.ts::EmbeddingService"],
    },
    "tag_core": {
        "path": "Codebase/packages/frontend/core/src/modules/tag",
        "classification": "PARTIAL_REUSABLE_FOUNDATION",
        "reason": "Stable tag IDs and memberships in workspace metadata; requires ordinary-file serialization.",
        "anchors": ["stores/tag.ts::TagStore", "entities/tag.ts::Tag"],
    },
    "workspace_trash": {
        "path": "Codebase/packages/frontend/apps/electron/src/helper/workspace/handlers.ts",
        "classification": "PARTIAL_REUSABLE_FOUNDATION",
        "reason": "Whole-workspace SQLite trash/import/recovery precedent, not app-independent file-backed restoration.",
        "anchors": ["handlers.ts::trashWorkspace", "handlers.ts::recoverWorkspace"],
    },
    "db_export": {
        "path": "Codebase/packages/frontend/apps/electron/src/helper/dialog/dialog.ts",
        "classification": "ADJACENT_IMPLEMENTATION",
        "reason": "Database export/vacuum-to-temporary precedent; not a general atomic ordinary-file writer.",
        "anchors": ["dialog.ts::saveDBFileAs"],
    },
}


DOMAIN_TESTS = {
    "CALENDAR": [
        "offline event creation and editing",
        "all-day and ranged events",
        "recurrence rules and exceptions",
        "time-zone and daylight-saving behavior",
        "reminder restart recovery",
        "task/deadline projection",
        "journal integration",
        "ICS import/export and duplicate detection",
        "folder-scoped and workspace-global views",
    ],
    "FINANCE": [
        "account balance derivation",
        "income, expense, transfer, and transfer reversal",
        "categories and recurring transactions",
        "bill calendar projections and reminders",
        "budgets, goals, receipts, and dashboards",
        "CSV dry run, import, duplicate detection, rollback, and export",
        "multi-currency storage without implicit conversion",
        "privacy and app-deletion survival",
    ],
    "CANVAS": [
        "folder and workspace ownership",
        "movement between scopes with stable IDs and backlinks",
        "asset ownership after movement",
        "Folder Home Canvas and Workspace Home Canvas",
        "scoped dynamic folder blocks",
        "export, recovery, and app-deletion survival",
    ],
    "MIND_MAP": [
        "independent editing and page/folder/workspace scope",
        "federated aggregation with no duplication",
        "source-map update propagation and filtering",
        "stable node IDs and cross-folder references",
        "export, recovery, accepted links, rejected suggestions, and provenance",
    ],
    "KNOWLEDGE": [
        "automatic structural relationships",
        "explicit links and automatic backlinks",
        "local semantic suggestions with no silent acceptance",
        "persisted rejection/dismissal decisions",
        "manual conceptual links and nonauthoritative temporary context",
        "movement without broken links",
        "reconstruction from files, provenance, confidence, and filters",
    ],
}

CAPABILITY_SPECIFIC_TESTS = {
    "MR-CAP-111": ["local file-backed calendar event persistence", "offline event store initialization", "atomic write and corruption recovery"],
    "MR-CAP-112": ["folder-scoped calendar view filtering", "workspace-global calendar aggregation", "calendar view selection state persistence"],
    "MR-CAP-113": ["all-day and time-ranged event modeling", "event duration validation", "event metadata and location field persistence"],
    "MR-CAP-114": ["RRULE RFC 5545 expansion correctness", "recurrence EXDATE and RECURRENCE-ID overrides", "leap year and DST recurrence expansion"],
    "MR-CAP-115": ["time-zone preservation across event saves", "daylight saving transition boundary tests", "UTC offset conversion and presentation isolation"],
    "MR-CAP-116": ["local notification scheduling on event time", "reminder restart and app-launch recovery", "snooze and dismissal state persistence"],
    "MR-CAP-117": ["task deadline projection onto calendar", "task completion toggle from calendar view", "bidirectional task-event sync"],
    "MR-CAP-118": ["journal date-to-calendar projection", "journal entry event linking", "daily note event badge rendering"],
    "MR-CAP-119": ["ICS file import parsing and validation", "ICS export round-trip fidelity", "duplicate event detection on ICS re-import"],
    "MR-CAP-120": ["external calendar credential zeroing and auth isolation", "synchronization conflict resolution without local data loss", "OAuth token expiration and failure handling", "adapter disablement and runtime disconnection", "remote deletion sync and local tombstone protection"],

    "MR-CAP-121": ["offline ledger initialization and atomic file persistence", "checksum verification of transaction log", "app deletion survival and backup recovery"],
    "MR-CAP-122": ["account balance derivation from transactions", "multi-account isolation and ledger scoping", "initial balance and credit line calculations"],
    "MR-CAP-123": ["income, expense, and transfer recording", "atomic transfer pair creation and reversal", "transaction audit log fidelity"],
    "MR-CAP-124": ["category hierarchy and tag assignment", "category breakdown balance reporting", "unassigned transaction handling"],
    "MR-CAP-125": ["recurring transaction rule generation", "upcoming recurring transaction projection", "recurring transaction skip and modification"],
    "MR-CAP-126": ["budget period cap definition", "budget overrun alert threshold calculation", "category-to-budget spend matching"],
    "MR-CAP-127": ["savings goal target date and progress tracking", "auto-contribution calculation", "goal milestone achievement detection"],
    "MR-CAP-128": ["receipt file attachment checksum verification", "receipt image OCR text extraction isolation", "transaction-receipt attachment deletion survival"],
    "MR-CAP-129": ["financial dashboard metric aggregation", "income vs expense chart projection", "privacy boundary on dashboard display"],
    "MR-CAP-130": ["CSV dry-run validation and row mapping", "CSV import quote-escaping and duplicate detection", "CSV rollback and transaction batch reversal"],
    "MR-CAP-131": ["multi-currency transaction storage without implicit conversion", "exchange rate snapshot recording", "presentation currency formatting"],
    "MR-CAP-132": ["local key storage and electron safeStorage isolation", "financial data encryption at rest", "app-lock and pin protection"],
    "MR-CAP-133": ["bill calendar event projection", "due date payment reminder trigger", "calendar-finance link integrity"],

    "MR-CAP-134": ["page, folder, and workspace canvas ownership scoping", "scoped canvas access policy", "canvas document lifecycle"],
    "MR-CAP-135": ["independent whiteboard file bundle creation", "whiteboard board.json metadata validation", "whiteboard element rendering without cloud coupling"],
    "MR-CAP-136": ["Folder Home Canvas initialization", "folder content auto-summary element generation", "Folder Home Canvas deletion protection"],
    "MR-CAP-137": ["Workspace Home Canvas aggregation", "multi-folder quick nav element rendering", "Workspace Home Canvas recovery"],
    "MR-CAP-138": ["dynamic folder block query execution", "descendant page auto-embedding", "folder block filter update propagation"],
    "MR-CAP-139": ["atomic canvas file movement between folders", "stable identity preservation after canvas move", "asset folder migration on move"],
    "MR-CAP-140": ["board.json and asset directory bundle layout", "canvas preview image generation", "corrupted canvas recovery from journal"],
    "MR-CAP-141": ["cross-folder canvas reference locator resolution", "broken reference alias fallback", "orphaned canvas element garbage collection"],

    "MR-CAP-142": ["independent mind-map file bundle creation", "mind-map.json metadata validation", "non-AI mind-map node tree rendering"],
    "MR-CAP-143": ["page-embedded mind-map block rendering", "page doc mind-map node sync", "page mind-map export"],
    "MR-CAP-144": ["folder-scoped mind-map document creation", "folder page auto-node generation", "folder mind-map ownership"],
    "MR-CAP-145": ["workspace-scoped mind-map library management", "workspace mind-map index maintenance", "workspace mind-map access control"],
    "MR-CAP-146": ["folder knowledge map relationship projection", "folder doc link-to-node mapping", "folder knowledge map layout recalculation"],
    "MR-CAP-147": ["federated global knowledge map view generation", "non-duplicating source node aggregation", "global map filter and zoom performance"],
    "MR-CAP-148": ["source mind-map update propagation to global view", "non-authoritative global edit guard", "source map disconnect handling"],
    "MR-CAP-149": ["map-of-maps cluster navigation", "cluster drill-down and back navigation", "sub-map preview rendering"],
    "MR-CAP-150": ["mind-map bundle file serialization", "asset and icon packaging in mind-map bundle", "mind-map recovery from journal"],
    "MR-CAP-151": ["mind-map node to knowledge graph edge projection", "node provenance tag propagation", "graph filter by mind-map source"],

    "MR-CAP-152": ["automatic structural relationship extraction from files", "containment and tag link detection", "structural edge confidence rating"],
    "MR-CAP-153": ["explicit Markdown link parsing", "automatic backlink index updates", "broken link detection and repair queue"],
    "MR-CAP-154": ["local FTS and lexical semantic suggestion generation", "explainable link suggestion score calculation", "offline suggestion engine isolation"],
    "MR-CAP-155": ["semantic suggestion accept and reject decision persistence", "prohibition of silent auto-acceptance", "dismissed suggestion suppression"],
    "MR-CAP-156": ["manual conceptual link creation and typing", "conceptual relationship metadata editing", "manual link provenance tracking"],
    "MR-CAP-157": ["temporary contextual link memory lifecycle", "non-persisted context link cleanup on session close", "isolation from authoritative graph"],
    "MR-CAP-158": ["relationship origin and timestamp recording", "confidence score calculation and display", "provenance filter execution"],
    "MR-CAP-159": ["global graph filter query execution", "tag, date, and scope graph filter combination", "filtered graph view export"],
    "MR-CAP-160": ["stable UUID generation and file header preservation", "file rename and relocation tracking", "cross-folder path alias resolution"],
    "MR-CAP-161": ["full graph reconstruction from visible workspace files", "SQLite index rebuild from ordinary Markdown", "app-deletion survival and graph recovery"],
}


CAPABILITIES = [
    # Calendar: MR-CAP-111..120
    {
        "name": "Local Calendar Core",
        "domain": "CALENDAR",
        "wave": "WAVE_2",
        "status": "PARTIAL_FOUNDATION_PRESENT",
        "sources": ["calendar_engine", "date_picker", "journal_core", "local_storage"],
        "target": "Codebase/packages/frontend/core/src/modules/mindroom-calendar/core",
        "commonTarget": "Codebase/packages/common/mindroom/src/calendar/core.ts",
        "changeType": "ADAPT",
        "dependencies": ["MR-CAP-160"],
        "absence": "No first-class local MindRoom calendar aggregate or ordinary-file event source of truth exists.",
    },
    {
        "name": "Calendar Ownership and Scoped Views",
        "domain": "CALENDAR",
        "wave": "WAVE_2",
        "status": "PARTIAL_FOUNDATION_PRESENT",
        "sources": ["calendar_engine", "folder_organize"],
        "target": "Codebase/packages/frontend/core/src/modules/mindroom-calendar/ownership",
        "commonTarget": "Codebase/packages/common/mindroom/src/calendar/ownership.ts",
        "changeType": "ADD",
        "dependencies": ["MR-CAP-111", "MR-CAP-160"],
        "absence": "Database calendar views and logical folders exist, but page/folder/workspace calendar ownership does not.",
    },
    {
        "name": "Calendar Events",
        "domain": "CALENDAR",
        "wave": "WAVE_2",
        "status": "PARTIAL_FOUNDATION_PRESENT",
        "sources": ["calendar_engine", "calendar_workspace_bridge", "calendar_backend"],
        "target": "Codebase/packages/frontend/core/src/modules/mindroom-calendar/events",
        "commonTarget": "Codebase/packages/common/mindroom/src/calendar/event.ts",
        "changeType": "ADD",
        "dependencies": ["MR-CAP-111", "MR-CAP-112"],
        "absence": "Calendar row/external event projections exist, but no local durable MindRoom event entity exists.",
    },
    {
        "name": "Calendar Recurrence",
        "domain": "CALENDAR",
        "wave": "WAVE_2",
        "status": "ADJACENT_IMPLEMENTATION_PRESENT",
        "sources": ["calendar_backend"],
        "target": "Codebase/packages/frontend/core/src/modules/mindroom-calendar/recurrence",
        "commonTarget": "Codebase/packages/common/mindroom/src/calendar/recurrence.ts",
        "changeType": "ADD",
        "dependencies": ["MR-CAP-113"],
        "absence": "Provider recurrence IDs are adjacent ingestion evidence; no local recurrence rule/exception engine exists.",
    },
    {
        "name": "Calendar Time Zones",
        "domain": "CALENDAR",
        "wave": "WAVE_2",
        "status": "ADJACENT_IMPLEMENTATION_PRESENT",
        "sources": ["calendar_engine", "calendar_backend"],
        "target": "Codebase/packages/frontend/core/src/modules/mindroom-calendar/time-zones",
        "commonTarget": "Codebase/packages/common/mindroom/src/calendar/time-zone.ts",
        "changeType": "ADD",
        "dependencies": ["MR-CAP-113", "MR-CAP-114"],
        "absence": "View and provider timestamps exist, but no canonical local zone-preserving calendar domain contract exists.",
    },
    {
        "name": "Calendar Reminders and Notifications",
        "domain": "CALENDAR",
        "wave": "WAVE_2",
        "status": "ABSENT_PLANNED_ADDITION",
        "sources": [],
        "target": "Codebase/packages/frontend/core/src/modules/mindroom-calendar/reminders",
        "commonTarget": "Codebase/packages/common/mindroom/src/calendar/reminder.ts",
        "changeType": "ADD",
        "dependencies": ["MR-CAP-113", "MR-CAP-115"],
        "absence": "No source-inspected local calendar reminder scheduler or restart-recovery contract exists.",
    },
    {
        "name": "Task and Deadline Calendar Integration",
        "domain": "CALENDAR",
        "wave": "WAVE_2",
        "status": "ADJACENT_IMPLEMENTATION_PRESENT",
        "sources": ["data_view_properties", "calendar_engine"],
        "target": "Codebase/packages/frontend/core/src/modules/mindroom-calendar/tasks",
        "commonTarget": "Codebase/packages/common/mindroom/src/calendar/task-projection.ts",
        "changeType": "ADD",
        "dependencies": ["MR-CAP-113", "MR-CAP-160"],
        "absence": "Date properties can project rows, but no stable task/deadline entity integration exists.",
    },
    {
        "name": "Journal Calendar Integration",
        "domain": "CALENDAR",
        "wave": "WAVE_2",
        "status": "PARTIAL_FOUNDATION_PRESENT",
        "sources": ["journal_core", "journal_calendar_ui", "calendar_engine"],
        "target": "Codebase/packages/frontend/core/src/modules/mindroom-calendar/journal",
        "commonTarget": "Codebase/packages/common/mindroom/src/calendar/journal-projection.ts",
        "changeType": "ADAPT",
        "dependencies": ["MR-CAP-111", "MR-CAP-113"],
        "absence": "Journal date identity exists; event UI currently consumes a cloud integration boundary.",
    },
    {
        "name": "ICS Import and Export",
        "domain": "CALENDAR",
        "wave": "WAVE_2",
        "status": "ADJACENT_IMPLEMENTATION_PRESENT",
        "sources": ["calendar_backend"],
        "target": "Codebase/packages/frontend/core/src/modules/mindroom-calendar/ics",
        "commonTarget": "Codebase/packages/common/mindroom/src/calendar/ics.ts",
        "changeType": "ADD",
        "dependencies": ["MR-CAP-113", "MR-CAP-114", "MR-CAP-115"],
        "absence": "CalDAV provider parsing is remote-adapter evidence; no general offline ICS import/export pipeline exists.",
    },
    {
        "name": "Optional External Calendar Adapters",
        "domain": "CALENDAR",
        "wave": "WAVE_5",
        "status": "ADJACENT_IMPLEMENTATION_PRESENT",
        "sources": ["calendar_workspace_bridge", "calendar_integration", "calendar_backend", "calendar_graphql"],
        "target": "Codebase/packages/frontend/core/src/modules/mindroom-calendar/adapters",
        "commonTarget": "Codebase/packages/common/mindroom/src/calendar/adapter-contract.ts",
        "changeType": "ADAPT",
        "dependencies": ["MR-CAP-111", "MR-CAP-119"],
        "absence": "Existing adapters are cloud/server coupled and cannot be a dependency of the local core.",
    },
    # Finance: MR-CAP-121..133
    {
        "name": "MindRoom Finance Core",
        "domain": "FINANCE",
        "wave": "WAVE_3",
        "status": "PARTIAL_FOUNDATION_PRESENT",
        "sources": ["database_model", "database_block", "data_view_table", "local_storage", "payment_system"],
        "target": "Codebase/packages/frontend/core/src/modules/mindroom-finance/core",
        "commonTarget": "Codebase/packages/common/mindroom/src/finance/core.ts",
        "changeType": "ADD",
        "dependencies": ["MR-CAP-160", "MR-CAP-132"],
        "absence": "Reusable database and local-storage foundations exist; no finance ledger/domain implementation exists. Payment is excluded-system evidence.",
    },
    {
        "name": "Financial Accounts",
        "domain": "FINANCE",
        "wave": "WAVE_3",
        "status": "PARTIAL_FOUNDATION_PRESENT",
        "sources": ["database_model", "data_view_table", "data_view_properties"],
        "target": "Codebase/packages/frontend/core/src/modules/mindroom-finance/accounts",
        "commonTarget": "Codebase/packages/common/mindroom/src/finance/account.ts",
        "changeType": "ADD",
        "dependencies": ["MR-CAP-121"],
        "absence": "Generic rows and fields exist; no stable financial-account entity or balance contract exists.",
    },
    {
        "name": "Transactions and Transfers",
        "domain": "FINANCE",
        "wave": "WAVE_3",
        "status": "PARTIAL_FOUNDATION_PRESENT",
        "sources": ["database_model", "data_view_table", "data_view_statistics"],
        "target": "Codebase/packages/frontend/core/src/modules/mindroom-finance/transactions",
        "commonTarget": "Codebase/packages/common/mindroom/src/finance/transaction.ts",
        "changeType": "ADD",
        "dependencies": ["MR-CAP-121", "MR-CAP-122"],
        "absence": "No ledger, transfer-pair identity, reversal, reconciliation, or audit implementation exists.",
    },
    {
        "name": "Finance Categories and Tags",
        "domain": "FINANCE",
        "wave": "WAVE_3",
        "status": "PARTIAL_FOUNDATION_PRESENT",
        "sources": ["data_view_properties", "tag_core"],
        "target": "Codebase/packages/frontend/core/src/modules/mindroom-finance/categories",
        "commonTarget": "Codebase/packages/common/mindroom/src/finance/category.ts",
        "changeType": "ADAPT",
        "dependencies": ["MR-CAP-121", "MR-CAP-160"],
        "absence": "Reusable select/tag IDs exist but lack file-backed finance ownership.",
    },
    {
        "name": "Recurring Bills and Income",
        "domain": "FINANCE",
        "wave": "WAVE_3",
        "status": "ADJACENT_IMPLEMENTATION_PRESENT",
        "sources": ["calendar_engine", "data_view_properties"],
        "target": "Codebase/packages/frontend/core/src/modules/mindroom-finance/recurring",
        "commonTarget": "Codebase/packages/common/mindroom/src/finance/recurring.ts",
        "changeType": "ADD",
        "dependencies": ["MR-CAP-123", "MR-CAP-114"],
        "absence": "Dates and calendar projections exist; no recurring financial rule or projection lifecycle exists.",
    },
    {
        "name": "Budgets",
        "domain": "FINANCE",
        "wave": "WAVE_3",
        "status": "PARTIAL_FOUNDATION_PRESENT",
        "sources": ["data_view_statistics", "data_view_properties", "data_view_expression_false_positive"],
        "target": "Codebase/packages/frontend/core/src/modules/mindroom-finance/budgets",
        "commonTarget": "Codebase/packages/common/mindroom/src/finance/budget.ts",
        "changeType": "ADD",
        "dependencies": ["MR-CAP-123", "MR-CAP-124"],
        "absence": "Display statistics are reusable; no accounting-safe budget engine or formula implementation exists.",
    },
    {
        "name": "Savings Goals",
        "domain": "FINANCE",
        "wave": "WAVE_5",
        "status": "PARTIAL_FOUNDATION_PRESENT",
        "sources": ["data_view_properties", "data_view_statistics"],
        "target": "Codebase/packages/frontend/core/src/modules/mindroom-finance/goals",
        "commonTarget": "Codebase/packages/common/mindroom/src/finance/goal.ts",
        "changeType": "ADD",
        "dependencies": ["MR-CAP-122", "MR-CAP-123"],
        "absence": "Number/progress UI exists; no savings-goal entity, contribution, or target-date behavior exists.",
    },
    {
        "name": "Receipts and Financial Attachments",
        "domain": "FINANCE",
        "wave": "WAVE_3",
        "status": "PARTIAL_FOUNDATION_PRESENT",
        "sources": ["attachment_model", "attachment_block"],
        "target": "Codebase/packages/frontend/core/src/modules/mindroom-finance/receipts",
        "commonTarget": "Codebase/packages/common/mindroom/src/finance/receipt.ts",
        "changeType": "ADAPT",
        "dependencies": ["MR-CAP-123", "MR-CAP-160"],
        "absence": "Attachment primitives exist; checksum, ownership, transaction link, file export, and recovery contracts do not.",
    },
    {
        "name": "Financial Dashboards",
        "domain": "FINANCE",
        "wave": "WAVE_5",
        "status": "PARTIAL_FOUNDATION_PRESENT",
        "sources": ["chart_primitive", "data_view_statistics", "analytics_excluded"],
        "target": "Codebase/packages/frontend/core/src/modules/mindroom-finance/dashboards",
        "commonTarget": "Codebase/packages/common/mindroom/src/finance/dashboard-projection.ts",
        "changeType": "ADD",
        "dependencies": ["MR-CAP-122", "MR-CAP-123", "MR-CAP-126"],
        "absence": "Recharts and generic statistics exist; cloud analytics/paywall is excluded and no finance dashboard exists.",
    },
    {
        "name": "Finance CSV Import and Export",
        "domain": "FINANCE",
        "wave": "WAVE_3",
        "status": "ADJACENT_IMPLEMENTATION_PRESENT",
        "sources": ["csv_adjacent"],
        "target": "Codebase/packages/frontend/core/src/modules/mindroom-finance/csv",
        "commonTarget": "Codebase/packages/common/mindroom/src/finance/csv.ts",
        "changeType": "ADD",
        "dependencies": ["MR-CAP-122", "MR-CAP-123"],
        "absence": "Adjacent CSV helper is not quote-safe and lacks mappings, dry runs, duplicates, rollback, or receipts.",
    },
    {
        "name": "Multi-Currency Foundation",
        "domain": "FINANCE",
        "wave": "WAVE_5",
        "status": "PARTIAL_FOUNDATION_PRESENT",
        "sources": ["data_view_properties"],
        "target": "Codebase/packages/frontend/core/src/modules/mindroom-finance/currency",
        "commonTarget": "Codebase/packages/common/mindroom/src/finance/money.ts",
        "changeType": "ADD",
        "dependencies": ["MR-CAP-123"],
        "absence": "Locale formatting and fixed currency variants are presentation-only; no canonical money/precision/exchange-rate model exists.",
    },
    {
        "name": "Finance Privacy and Local Protection",
        "domain": "FINANCE",
        "wave": "WAVE_0",
        "status": "ADJACENT_IMPLEMENTATION_PRESENT",
        "sources": ["safe_storage", "safe_json_storage", "local_storage"],
        "target": "Codebase/packages/frontend/core/src/modules/mindroom-finance/privacy",
        "commonTarget": "Codebase/packages/common/mindroom/src/finance/protection-contract.ts",
        "changeType": "ADD",
        "dependencies": ["MR-CAP-160"],
        "absence": "A Windows/Electron encrypted-value precedent exists; cross-platform finance keys, locking, indexes, blobs, backup, and recovery are undecided.",
    },
    {
        "name": "Calendar–Finance Integration",
        "domain": "FINANCE",
        "wave": "WAVE_3",
        "status": "PARTIAL_FOUNDATION_PRESENT",
        "sources": ["calendar_engine", "data_view_table"],
        "target": "Codebase/packages/frontend/core/src/modules/mindroom-finance/calendar-projection",
        "commonTarget": "Codebase/packages/common/mindroom/src/finance/calendar-link.ts",
        "changeType": "ADD",
        "dependencies": ["MR-CAP-113", "MR-CAP-117", "MR-CAP-123", "MR-CAP-125"],
        "absence": "Calendar projections and table rows exist, but stable event/transaction links and projection policy do not.",
    },
    # Canvas: MR-CAP-134..141
    {
        "name": "Canvas Ownership and Scoping",
        "domain": "CANVAS",
        "wave": "WAVE_0",
        "status": "PARTIAL_FOUNDATION_PRESENT",
        "sources": ["edgeless_root", "surface_model", "gfx_framework", "folder_organize"],
        "target": "Codebase/packages/frontend/core/src/modules/mindroom-canvas-scope/ownership",
        "commonTarget": "Codebase/packages/common/mindroom/src/canvas/ownership.ts",
        "changeType": "WRAP",
        "dependencies": ["MR-CAP-160"],
        "absence": "Edgeless is a mode of a Yjs doc; no independent page/folder/workspace filesystem ownership layer exists.",
    },
    {
        "name": "Independent Whiteboard Documents",
        "domain": "CANVAS",
        "wave": "WAVE_1",
        "status": "PARTIAL_FOUNDATION_PRESENT",
        "sources": ["edgeless_root", "surface_model", "gfx_framework", "affine_gfx"],
        "target": "Codebase/packages/frontend/core/src/modules/mindroom-canvas-scope/whiteboard",
        "commonTarget": "Codebase/packages/common/mindroom/src/canvas/whiteboard.ts",
        "changeType": "WRAP",
        "dependencies": ["MR-CAP-134", "MR-CAP-140"],
        "absence": "Mature canvas behavior exists, but no independent whiteboard aggregate or ordinary-file bundle exists.",
    },
    {
        "name": "Folder Home Canvas",
        "domain": "CANVAS",
        "wave": "WAVE_1",
        "status": "ABSENT_PLANNED_ADDITION",
        "sources": ["edgeless_root", "folder_organize"],
        "target": "Codebase/packages/frontend/core/src/modules/mindroom-canvas-scope/folder-home",
        "commonTarget": "Codebase/packages/common/mindroom/src/canvas/folder-home.ts",
        "changeType": "ADD",
        "dependencies": ["MR-CAP-134", "MR-CAP-135"],
        "absence": "No source-inspected Folder Home Canvas ownership or storage implementation exists.",
    },
    {
        "name": "Workspace Home Canvas",
        "domain": "CANVAS",
        "wave": "WAVE_1",
        "status": "ABSENT_PLANNED_ADDITION",
        "sources": ["edgeless_root", "workspace_identity"],
        "target": "Codebase/packages/frontend/core/src/modules/mindroom-canvas-scope/workspace-home",
        "commonTarget": "Codebase/packages/common/mindroom/src/canvas/workspace-home.ts",
        "changeType": "ADD",
        "dependencies": ["MR-CAP-134", "MR-CAP-135"],
        "absence": "No source-inspected Workspace Home Canvas ownership or storage implementation exists.",
    },
    {
        "name": "Dynamic Folder-Content Canvas Blocks",
        "domain": "CANVAS",
        "wave": "WAVE_1",
        "status": "PARTIAL_FOUNDATION_PRESENT",
        "sources": ["collection_rules", "embed_doc", "surface_ref"],
        "target": "Codebase/packages/frontend/core/src/modules/mindroom-canvas-scope/folder-content-block",
        "commonTarget": "Codebase/packages/common/mindroom/src/canvas/folder-content-projection.ts",
        "changeType": "ADD",
        "dependencies": ["MR-CAP-136"],
        "absence": "Filters and embeds exist, but no descendant-aware folder projection block exists.",
    },
    {
        "name": "Canvas Movement and Stable Identity",
        "domain": "CANVAS",
        "wave": "WAVE_1",
        "status": "PARTIAL_FOUNDATION_PRESENT",
        "sources": ["id_generator", "surface_model", "folder_organize"],
        "target": "Codebase/packages/frontend/core/src/modules/mindroom-canvas-scope/movement",
        "commonTarget": "Codebase/packages/common/mindroom/src/canvas/movement.ts",
        "changeType": "ADD",
        "dependencies": ["MR-CAP-134", "MR-CAP-160"],
        "absence": "Element/doc IDs exist; atomic file movement, ownership transfer, aliasing, and reference repair do not.",
    },
    {
        "name": "Canvas File Persistence and Asset Ownership",
        "domain": "CANVAS",
        "wave": "WAVE_0",
        "status": "PARTIAL_FOUNDATION_PRESENT",
        "sources": ["surface_model", "attachment_model", "local_storage", "db_export"],
        "target": "Codebase/packages/frontend/core/src/modules/mindroom-canvas-scope/persistence",
        "commonTarget": "Codebase/packages/common/mindroom/src/canvas/bundle.ts",
        "changeType": "ADAPT",
        "dependencies": ["MR-CAP-160"],
        "absence": "Yjs/SQLite persistence exists; board.json, metadata, assets, previews, journal, and recovery bundle do not.",
    },
    {
        "name": "Cross-Folder Canvas References",
        "domain": "CANVAS",
        "wave": "WAVE_1",
        "status": "PARTIAL_FOUNDATION_PRESENT",
        "sources": ["surface_ref", "inline_reference", "embed_doc"],
        "target": "Codebase/packages/frontend/core/src/modules/mindroom-canvas-scope/references",
        "commonTarget": "Codebase/packages/common/mindroom/src/canvas/reference.ts",
        "changeType": "ADAPT",
        "dependencies": ["MR-CAP-134", "MR-CAP-138", "MR-CAP-160"],
        "absence": "Workspace-local refs exist; cross-folder file locators, aliases, and broken-reference recovery do not.",
    },
    # Mind maps: MR-CAP-142..151
    {
        "name": "Independent Mind-Map Documents",
        "domain": "MIND_MAP",
        "wave": "WAVE_1",
        "status": "PARTIAL_FOUNDATION_PRESENT",
        "sources": ["mindmap_model", "mindmap_gfx", "mindmap_registration", "mindmap_ai"],
        "target": "Codebase/packages/frontend/core/src/modules/mindroom-knowledge-graph/mind-maps/independent",
        "commonTarget": "Codebase/packages/common/mindroom/src/mind-map/document.ts",
        "changeType": "WRAP",
        "dependencies": ["MR-CAP-150", "MR-CAP-160"],
        "absence": "The real non-AI element/layout engine exists; an independently owned file-backed document does not.",
    },
    {
        "name": "Page-Scoped Mind Maps",
        "domain": "MIND_MAP",
        "wave": "WAVE_1",
        "status": "FULL_IMPLEMENTATION_PRESENT",
        "sources": ["mindmap_model", "mindmap_gfx", "mindmap_registration"],
        "target": "Codebase/packages/frontend/core/src/modules/mindroom-knowledge-graph/mind-maps/page-scope",
        "commonTarget": "Codebase/packages/common/mindroom/src/mind-map/page-scope.ts",
        "changeType": "ADAPT",
        "dependencies": ["MR-CAP-142", "MR-CAP-160"],
        "absence": "Mind maps already live in BlockSuite docs; file-backed page ownership metadata remains to add.",
    },
    {
        "name": "Folder-Scoped Mind Maps",
        "domain": "MIND_MAP",
        "wave": "WAVE_1",
        "status": "ABSENT_PLANNED_ADDITION",
        "sources": ["mindmap_model", "folder_organize"],
        "target": "Codebase/packages/frontend/core/src/modules/mindroom-knowledge-graph/mind-maps/folder-scope",
        "commonTarget": "Codebase/packages/common/mindroom/src/mind-map/folder-scope.ts",
        "changeType": "ADD",
        "dependencies": ["MR-CAP-142", "MR-CAP-160"],
        "absence": "No file-backed folder-owned mind-map document implementation exists.",
    },
    {
        "name": "Workspace Mind Maps",
        "domain": "MIND_MAP",
        "wave": "WAVE_1",
        "status": "ABSENT_PLANNED_ADDITION",
        "sources": ["mindmap_model", "workspace_identity"],
        "target": "Codebase/packages/frontend/core/src/modules/mindroom-knowledge-graph/mind-maps/workspace-scope",
        "commonTarget": "Codebase/packages/common/mindroom/src/mind-map/workspace-scope.ts",
        "changeType": "ADD",
        "dependencies": ["MR-CAP-142", "MR-CAP-160"],
        "absence": "No file-backed workspace-library mind-map ownership implementation exists.",
    },
    {
        "name": "Folder Knowledge Map",
        "domain": "MIND_MAP",
        "wave": "WAVE_1",
        "status": "ABSENT_PLANNED_ADDITION",
        "sources": ["mindmap_model", "folder_organize", "doc_links"],
        "target": "Codebase/packages/frontend/core/src/modules/mindroom-knowledge-graph/mind-maps/folder-knowledge-map",
        "commonTarget": "Codebase/packages/common/mindroom/src/mind-map/folder-knowledge-map.ts",
        "changeType": "ADD",
        "dependencies": ["MR-CAP-144", "MR-CAP-152", "MR-CAP-153"],
        "absence": "No folder-scope relationship projection into a local knowledge map exists.",
    },
    {
        "name": "Workspace Global Knowledge Map",
        "domain": "MIND_MAP",
        "wave": "WAVE_4",
        "status": "ABSENT_PLANNED_ADDITION",
        "sources": ["mindmap_model", "doc_links", "sqlite_indexer"],
        "target": "Codebase/packages/frontend/core/src/modules/mindroom-knowledge-graph/global-map",
        "commonTarget": "Codebase/packages/common/mindroom/src/mind-map/global-map.ts",
        "changeType": "ADD",
        "dependencies": ["MR-CAP-145", "MR-CAP-148", "MR-CAP-152"],
        "absence": "No federated nonduplicating workspace global map implementation exists.",
    },
    {
        "name": "Federated Mind-Map Aggregation",
        "domain": "MIND_MAP",
        "wave": "WAVE_4",
        "status": "ABSENT_PLANNED_ADDITION",
        "sources": ["mindmap_model", "sqlite_indexer"],
        "target": "Codebase/packages/frontend/core/src/modules/mindroom-knowledge-graph/federation",
        "commonTarget": "Codebase/packages/common/mindroom/src/mind-map/federation.ts",
        "changeType": "ADD",
        "dependencies": ["MR-CAP-142", "MR-CAP-146", "MR-CAP-158", "MR-CAP-161"],
        "absence": "No source-map federation/projection layer exists; source maps must remain authoritative.",
    },
    {
        "name": "Map-of-Maps Navigation",
        "domain": "MIND_MAP",
        "wave": "WAVE_1",
        "status": "PARTIAL_FOUNDATION_PRESENT",
        "sources": ["inline_reference", "linked_doc", "mindmap_model"],
        "target": "Codebase/packages/frontend/core/src/modules/mindroom-knowledge-graph/map-navigation",
        "commonTarget": "Codebase/packages/common/mindroom/src/mind-map/navigation.ts",
        "changeType": "ADAPT",
        "dependencies": ["MR-CAP-142", "MR-CAP-143", "MR-CAP-144", "MR-CAP-145"],
        "absence": "Linked-doc navigation exists; map-node-to-map stable navigation and recovery do not.",
    },
    {
        "name": "Mind-Map File Persistence",
        "domain": "MIND_MAP",
        "wave": "WAVE_1",
        "status": "PARTIAL_FOUNDATION_PRESENT",
        "sources": ["mindmap_model", "mindmap_gfx", "local_storage", "db_export"],
        "target": "Codebase/packages/frontend/core/src/modules/mindroom-knowledge-graph/mind-maps/persistence",
        "commonTarget": "Codebase/packages/common/mindroom/src/mind-map/bundle.ts",
        "changeType": "ADAPT",
        "dependencies": ["MR-CAP-160"],
        "absence": "Element snapshots/adapters exist; mind-map.json, metadata, assets, previews, journal, and recovery bundle do not.",
    },
    {
        "name": "Mind-Map Projection into Knowledge Graph",
        "domain": "MIND_MAP",
        "wave": "WAVE_4",
        "status": "PARTIAL_FOUNDATION_PRESENT",
        "sources": ["mindmap_model", "reader_refs", "sqlite_indexer"],
        "target": "Codebase/packages/frontend/core/src/modules/mindroom-knowledge-graph/mind-map-projection",
        "commonTarget": "Codebase/packages/common/mindroom/src/mind-map/graph-projection.ts",
        "changeType": "ADD",
        "dependencies": ["MR-CAP-142", "MR-CAP-148", "MR-CAP-158", "MR-CAP-161"],
        "absence": "Mind-map tree and local index exist; provenance-preserving graph projection does not.",
    },
    # Knowledge / identity / recovery: MR-CAP-152..161
    {
        "name": "Automatic Structural Relationships",
        "domain": "KNOWLEDGE",
        "wave": "WAVE_1",
        "status": "PARTIAL_FOUNDATION_PRESENT",
        "sources": ["reference_model", "doc_links", "reader_refs", "tag_core", "database_model"],
        "target": "Codebase/packages/frontend/core/src/modules/mindroom-relationships/structural",
        "commonTarget": "Codebase/packages/common/mindroom/src/relationships/structural.ts",
        "changeType": "ADAPT",
        "dependencies": ["MR-CAP-158", "MR-CAP-160"],
        "absence": "References/tags/DB structure exist, but complete file-derived relationship extraction and provenance do not.",
    },
    {
        "name": "Explicit Links and Automatic Backlinks",
        "domain": "KNOWLEDGE",
        "wave": "WAVE_1",
        "status": "PARTIAL_FOUNDATION_PRESENT",
        "sources": ["reference_model", "inline_reference", "doc_links", "reader_refs", "indexer_schema"],
        "target": "Codebase/packages/frontend/core/src/modules/mindroom-relationships/explicit-links",
        "commonTarget": "Codebase/packages/common/mindroom/src/relationships/explicit.ts",
        "changeType": "ADAPT",
        "dependencies": ["MR-CAP-152", "MR-CAP-160", "MR-CAP-161"],
        "absence": "Workspace-local refs/backlinks exist; file encoding, move repair, broken-link quarantine, and rebuild-from-files do not.",
    },
    {
        "name": "Local Semantic-Link Suggestions",
        "domain": "KNOWLEDGE",
        "wave": "WAVE_4",
        "status": "ABSENT_PLANNED_ADDITION",
        "sources": ["sqlite_indexer", "embedding_cloud"],
        "target": "Codebase/packages/frontend/core/src/modules/mindroom-relationships/semantic-suggestions",
        "commonTarget": "Codebase/packages/common/mindroom/src/relationships/semantic-suggestion.ts",
        "changeType": "ADD",
        "dependencies": ["MR-CAP-158", "MR-CAP-161"],
        "absence": "Local FTS exists; current embeddings are cloud/AI-coupled and no local explainable link-suggestion engine exists.",
    },
    {
        "name": "Semantic-Link Review and Confirmation",
        "domain": "KNOWLEDGE",
        "wave": "WAVE_4",
        "status": "ABSENT_PLANNED_ADDITION",
        "sources": ["inline_reference", "sqlite_indexer"],
        "target": "Codebase/packages/frontend/core/src/modules/mindroom-relationships/semantic-review",
        "commonTarget": "Codebase/packages/common/mindroom/src/relationships/semantic-decision.ts",
        "changeType": "ADD",
        "dependencies": ["MR-CAP-154", "MR-CAP-158", "MR-CAP-160"],
        "absence": "No accept/reject/dismiss workflow, durable decision record, or silent-acceptance guard exists.",
    },
    {
        "name": "Manual Conceptual Relationships",
        "domain": "KNOWLEDGE",
        "wave": "WAVE_1",
        "status": "PARTIAL_FOUNDATION_PRESENT",
        "sources": ["inline_reference", "linked_doc", "reference_model"],
        "target": "Codebase/packages/frontend/core/src/modules/mindroom-relationships/manual",
        "commonTarget": "Codebase/packages/common/mindroom/src/relationships/manual.ts",
        "changeType": "ADAPT",
        "dependencies": ["MR-CAP-153", "MR-CAP-158", "MR-CAP-160"],
        "absence": "Explicit refs exist; typed manual conceptual relationships and file-backed provenance do not.",
    },
    {
        "name": "Temporary Contextual Relationships",
        "domain": "KNOWLEDGE",
        "wave": "WAVE_4",
        "status": "ABSENT_PLANNED_ADDITION",
        "sources": ["sqlite_indexer"],
        "target": "Codebase/packages/frontend/core/src/modules/mindroom-relationships/temporary-context",
        "commonTarget": "Codebase/packages/common/mindroom/src/relationships/temporary.ts",
        "changeType": "ADD",
        "dependencies": ["MR-CAP-154", "MR-CAP-158"],
        "absence": "No explicitly nonauthoritative, nonpersistent contextual relationship contract exists.",
    },
    {
        "name": "Relationship Provenance and Confidence",
        "domain": "KNOWLEDGE",
        "wave": "WAVE_0",
        "status": "PARTIAL_FOUNDATION_PRESENT",
        "sources": ["reader_refs", "indexer_schema", "reference_model"],
        "target": "Codebase/packages/frontend/core/src/modules/mindroom-relationships/provenance",
        "commonTarget": "Codebase/packages/common/mindroom/src/relationships/provenance.ts",
        "changeType": "ADD",
        "dependencies": ["MR-CAP-160"],
        "absence": "Source references exist, but unified relationship origin, evidence, confidence, timestamp, and review status do not.",
    },
    {
        "name": "Global Knowledge-Graph Filters",
        "domain": "KNOWLEDGE",
        "wave": "WAVE_4",
        "status": "PARTIAL_FOUNDATION_PRESENT",
        "sources": ["sqlite_indexer", "data_view_properties", "tag_core"],
        "target": "Codebase/packages/frontend/core/src/modules/mindroom-knowledge-graph/filters",
        "commonTarget": "Codebase/packages/common/mindroom/src/relationships/filter.ts",
        "changeType": "ADD",
        "dependencies": ["MR-CAP-152", "MR-CAP-158", "MR-CAP-161"],
        "absence": "Local query/filter primitives exist; typed global graph filters over provenance and scope do not.",
    },
    {
        "name": "Stable Identity Across File Movement",
        "domain": "KNOWLEDGE",
        "wave": "WAVE_0",
        "status": "PARTIAL_FOUNDATION_PRESENT",
        "sources": ["id_generator", "workspace_identity", "doc_identity", "folder_organize"],
        "target": "Codebase/packages/frontend/core/src/modules/workspace-files/identity",
        "commonTarget": "Codebase/packages/common/mindroom/src/stable-identity/index.ts",
        "changeType": "ADAPT",
        "dependencies": ["MR-CAP-031", "MR-CAP-032"],
        "absence": "Stable in-app IDs exist; filesystem locator, path aliases, ownership transfer, and cross-object move repair do not.",
    },
    {
        "name": "Knowledge-Graph Reconstruction and Recovery",
        "domain": "KNOWLEDGE",
        "wave": "WAVE_0",
        "status": "PARTIAL_FOUNDATION_PRESENT",
        "sources": ["reader_refs", "sqlite_indexer", "workspace_trash", "db_export"],
        "target": "Codebase/packages/frontend/core/src/modules/mindroom-knowledge-graph/recovery",
        "commonTarget": "Codebase/packages/common/mindroom/src/relationships/reconstruction.ts",
        "changeType": "ADD",
        "dependencies": ["MR-CAP-158", "MR-CAP-160"],
        "absence": "Derived index and SQLite recovery precedents exist; rebuild from visible ordinary files after app deletion does not.",
    },
]


LEGACY_SEMANTIC_CORRECTIONS = {
    "MR-CAP-007": {
        "name": "Edgeless mode",
        "status": "FULL_IMPLEMENTATION_PRESENT",
        "sources": ["edgeless_root", "surface_model", "gfx_framework", "affine_gfx"],
        "reason": "Replace fixed-size mixed candidates with the coherent BlockSuite Edgeless roots.",
    },
    "MR-CAP-008": {
        "name": "Infinite canvas",
        "status": "FULL_IMPLEMENTATION_PRESENT",
        "sources": ["edgeless_root", "surface_model", "gfx_framework", "affine_gfx"],
        "reason": "Exclude AI mini-mindmap and generic HTML canvas false positives.",
    },
    "MR-CAP-009": {
        "name": "Whiteboards",
        "status": "PARTIAL_FOUNDATION_PRESENT",
        "sources": ["edgeless_root", "surface_model", "gfx_framework", "affine_gfx"],
        "reason": "Mature canvas exists; independent file-backed whiteboard ownership remains absent.",
    },
    "MR-CAP-010": {
        "name": "Mind maps",
        "status": "FULL_IMPLEMENTATION_PRESENT",
        "sources": ["mindmap_model", "mindmap_gfx", "mindmap_registration", "mindmap_tests", "mindmap_ai"],
        "reason": "Use the real non-AI model/GFX roots and classify AI generation as excluded.",
    },
    "MR-CAP-011": {
        "name": "Database blocks",
        "status": "FULL_IMPLEMENTATION_PRESENT",
        "sources": ["database_model", "database_block", "data_view_block", "data_view_table"],
        "reason": "Replace mixed fixed-size candidates with coherent model/block/data-view roots.",
    },
    "MR-CAP-012": {
        "name": "Kanban",
        "status": "FULL_IMPLEMENTATION_PRESENT",
        "sources": ["database_model", "database_block", "data_view_block"],
        "reason": "Retain the database view engine; file-backed board/card ownership remains an adaptation.",
    },
    "MR-CAP-031": {
        "name": "Workspace identity",
        "status": "PARTIAL_FOUNDATION_PRESENT",
        "sources": ["workspace_identity", "id_generator"],
        "reason": "Stable IDs are present; filesystem ownership and aliases are planned.",
    },
    "MR-CAP-032": {
        "name": "Page identity",
        "status": "PARTIAL_FOUNDATION_PRESENT",
        "sources": ["doc_identity", "workspace_identity", "id_generator"],
        "reason": "Stable document IDs are present; filenames must remain nonidentity aliases.",
    },
    "MR-CAP-033": {
        "name": "Graph relationships",
        "status": "PARTIAL_FOUNDATION_PRESENT",
        "sources": ["reference_model", "inline_reference", "doc_links", "reader_refs", "indexer_schema", "tag_core"],
        "reason": "Use explicit link/backlink/tag/index roots, not GraphQL, AI, or preference false positives.",
    },
    "MR-CAP-096": {
        "name": "Rebuildable search",
        "status": "PARTIAL_FOUNDATION_PRESENT",
        "sources": ["reader_refs", "sqlite_indexer", "indexer_schema"],
        "reason": "Local index exists as derived state; rebuild from visible workspace files remains planned.",
    },
    "MR-CAP-097": {
        "name": "Rebuildable graph",
        "status": "PARTIAL_FOUNDATION_PRESENT",
        "sources": ["reference_model", "doc_links", "reader_refs", "sqlite_indexer", "tag_core"],
        "reason": "Relationship extraction/index foundations exist; app-independent graph reconstruction remains planned.",
    },
}


ADR_SPECS = [
    ("0001", "Canonical file-backed source of truth", "ACCEPTED", "Ordinary visible files and bundle metadata are authoritative; CRDT, SQLite, search, and graph stores are rebuildable derived/editing state."),
    ("0002", "Canvas bundle format", "ACCEPTED", "Use a versioned whiteboard bundle with board.json, metadata, owned assets, previews, journal, and recovery while retaining BlockSuite as the model/renderer."),
    ("0003", "Mind-map bundle format", "ACCEPTED", "Use a versioned mind-map bundle with mind-map.json, metadata, owned assets, previews, journal, and recovery around the retained non-AI BlockSuite model."),
    ("0004", "Global graph projection versus cache", "ACCEPTED", "The global graph is a computed federated projection/cache rebuilt from authoritative source files and local maps; it must not duplicate source-map ownership."),
    ("0005", "Stable IDs and path aliases", "ACCEPTED", "Preserve existing compatible IDs, generate stable IDs for new durable entities, keep paths nonauthoritative, and record historical aliases when useful."),
    ("0006", "Local semantic-index technology", "ACCEPTED", "Benchmark local candidates for recall, explanation, latency, recovery, package size, and privacy before selection."),
    ("0007", "Semantic suggestion persistence", "ACCEPTED", "Suggestions are derived; confirmations, rejections, dismissals, provenance, and confidence decisions are durable. Silent acceptance is forbidden."),
    ("0008", "Calendar recurrence representation", "ACCEPTED", "Choose a recurrence/exception representation with deterministic DST and ICS round-trip semantics."),
    ("0009", "Calendar file format and ICS compatibility", "ACCEPTED", "Choose canonical file-backed event/calendar representation and loss-aware ICS import/export rules."),
    ("0010", "Finance transaction storage format", "ACCEPTED", "Choose append-safe transaction, transfer-pair, correction, audit, and recovery formats with exact money semantics."),
    ("0011", "Finance encryption boundaries", "ACCEPTED", "Define cross-platform key lifecycle, lock behavior, blobs/indexes, backup, recovery, and failure behavior before implementation."),
    ("0012", "Multi-currency behavior", "ACCEPTED", "Define canonical amount/currency precision and prohibit implicit conversion until exchange-rate provenance is decided."),
    ("0013", "External calendar adapter boundaries", "ACCEPTED", "Adapters are optional, isolated, credential-minimizing projections and never dependencies of the local calendar core."),
    ("0014", "Folder and workspace inheritance behavior", "ACCEPTED", "Folders own scoped defaults and views; workspace views federate descendants without duplicating source ownership."),
]


RELATIONSHIP_TYPES = [
    ("OWNS", "MR-CAP-134", "MR-CAP-135"),
    ("BELONGS_TO", "MR-CAP-135", "MR-CAP-134"),
    ("CONTAINS", "MR-CAP-136", "MR-CAP-138"),
    ("SCOPED_TO", "MR-CAP-143", "MR-CAP-134"),
    ("INCLUDES_DESCENDANTS", "MR-CAP-136", "MR-CAP-138"),
    ("REFERENCES", "MR-CAP-141", "MR-CAP-153"),
    ("BACKLINK_FROM", "MR-CAP-153", "MR-CAP-141"),
    ("EMBEDS", "MR-CAP-135", "MR-CAP-141"),
    ("CONNECTED_ON_CANVAS", "MR-CAP-135", "MR-CAP-152"),
    ("PARENT_OF_MINDMAP_NODE", "MR-CAP-142", "MR-CAP-143"),
    ("PROJECTS_INTO_GLOBAL_MAP", "MR-CAP-146", "MR-CAP-147"),
    ("DERIVED_FROM_SOURCE_MAP", "MR-CAP-147", "MR-CAP-148"),
    ("LINKED_TO_EVENT", "MR-CAP-152", "MR-CAP-113"),
    ("LINKED_TO_TASK", "MR-CAP-152", "MR-CAP-117"),
    ("LINKED_TO_ACCOUNT", "MR-CAP-152", "MR-CAP-122"),
    ("LINKED_TO_TRANSACTION", "MR-CAP-152", "MR-CAP-123"),
    ("LINKED_TO_BUDGET", "MR-CAP-152", "MR-CAP-126"),
    ("LINKED_TO_GOAL", "MR-CAP-152", "MR-CAP-127"),
    ("ATTACHED_RECEIPT", "MR-CAP-123", "MR-CAP-128"),
    ("SUGGESTS_SEMANTIC_RELATION", "MR-CAP-154", "MR-CAP-155"),
    ("CONFIRMS_SEMANTIC_RELATION", "MR-CAP-155", "MR-CAP-156"),
    ("REJECTS_SEMANTIC_RELATION", "MR-CAP-155", "MR-CAP-158"),
    ("MANUAL_CONCEPTUAL_LINK", "MR-CAP-156", "MR-CAP-152"),
    ("GENERATES_VIEW", "MR-CAP-147", "MR-CAP-159"),
    ("REBUILDS_FROM", "MR-CAP-161", "MR-CAP-152"),
    ("IMPORTS_FROM_ICS", "MR-CAP-119", "MR-CAP-111"),
    ("EXPORTS_TO_ICS", "MR-CAP-111", "MR-CAP-119"),
    ("IMPORTS_FROM_CSV", "MR-CAP-130", "MR-CAP-121"),
    ("EXPORTS_TO_CSV", "MR-CAP-121", "MR-CAP-130"),
]


SEMANTIC_GATES = [
    "calendarRequirementsAdded",
    "calendarCapabilitiesAdded",
    "calendarFoundationsSourceInspected",
    "calendarCloudBoundaryMapped",
    "calendarFilePersistencePlanned",
    "calendarTestsMapped",
    "financeRequirementsAdded",
    "financeCapabilitiesAdded",
    "financeDistinguishedFromAffineBilling",
    "financeStoragePlanned",
    "financePrivacyMapped",
    "financeTestsMapped",
    "canvasScopeRequirementsAdded",
    "folderHomeCanvasMapped",
    "workspaceHomeCanvasMapped",
    "canvasMovementAndStableIdentityMapped",
    "canvasFilePersistenceMapped",
    "mindMapScopeRequirementsAdded",
    "folderMindMapsMapped",
    "workspaceMindMapsMapped",
    "globalFederatedMapMapped",
    "mapDuplicationProhibited",
    "realBlockSuiteMindMapRootsVerified",
    "aiMindMapRootsExcludedFromRetention",
    "structuralLinkingMapped",
    "explicitLinkingAndBacklinksMapped",
    "localSemanticSuggestionsMapped",
    "silentSemanticAcceptanceProhibited",
    "manualConceptualLinksMapped",
    "temporaryContextLinksSeparated",
    "relationshipProvenanceMapped",
    "globalGraphFiltersMapped",
    "stableIdentityModelMapped",
    "fileMovementDoesNotBreakLinksMapped",
    "folderAndWorkspaceOwnershipMapped",
    "calendarFinanceIntegrationMapped",
    "allNewRequirementsTraceable",
    "allNewCapabilitiesTraceable",
    "allNewChangesHaveExactTargets",
    "allNewTestsMapped",
    "releaseWavesUpdated",
    "oldCompletionSuperseded",
    "allDerivedArtifactsRegenerated",
    "independentReviewPassed",
    "codebaseUnmodified",
    "finalReleaseReceiptLocked",
    # Preservation amendment gates.
    "originalMasterPlanHeadingsPreserved",
    "originalRequirementsPreserved",
    "originalCapabilitiesPreserved",
    "originalRestrictionsPreserved",
    "noRequirementWeakening",
    "noUnauthorizedScopeReduction",
]

